### ISSUE TITLE
Rediscovered nodes do not join existing computation

### ISSUE THREAD

**Issue by nmoehrle** [pgiri/dispy#107]
If a node is [rediscovered](https://github.com/pgiri/dispy/blob/master/py3/dispy/__init__.py#L1592) all clusters it was previously part in are notified that this node is now closed and `node.clusters` is set to an empty set, however, the node is not removed from `*Cluster._dispy_nodes` so it is skipped in [`setup_node`](https://github.com/pgiri/dispy/blob/master/py3/dispy/__init__.py#L1530). This means that `node.clusters` and `*Cluster._dispy_nodes` are out of sync after that and that the status_callback is not called for these rediscovered nodes.

By poping the dispy_node from cluster._dispy_nodes ([here](https://github.com/pgiri/dispy/blob/master/py3/dispy/__init__.py#L1605)) the node would be setup and `_Node.clusters` and `Cluster._dispy_nodes` would be back in sync. Would that be the expected behavior?

I noted that this is what is happening in other places where nodes are closed:
https://github.com/pgiri/dispy/blob/master/py3/dispy/__init__.py#L1251,
https://github.com/pgiri/dispy/blob/master/py3/dispy/__init__.py#L1129

**Comment by pgiri** [comment]
Hmm, this is a bit tricky so let me take a look at it again (I believe I tested this, although quite some time ago). It may take couple of days to get back. I hope that is not a problem.

**Comment by nmoehrle** [comment]
No worries, I am really happy that you shared the code in the first place and I know what a burden maintenance can be... If you have something that I could look into, I'd be happy to help.

**Comment by pgiri** [comment]
Can you apply the patch attached and test?

[realloc.txt](https://github.com/pgiri/dispy/files/1765093/realloc.txt)

**Comment by pgiri** [comment]
The reason dispy_node is not removed from `_dispy_nodes` is that this structure is used to inform user space / http server about status of node, including time used etc. So if a dispy_node is removed, clients don't have a way of knowing that information after that node is closed. In the above patch dispy_node is removed when a node is rediscovered (at which point any information would've been for previous instance so okay to remove it).

**Comment by pgiri** [comment]
Have you been able to test the above patch?

**Comment by nmoehrle** [comment]
Thanks for checking back, I currently have to prepare some things that are necessary before I can start the next test, I'll give you feedback till the end of the week.

**Comment by nmoehrle** [comment]
We have been using the patch (in the form that I pushed) for a couple of runs now and it resolved the problem for us.
