### ISSUE TITLE
Windows does not allow binding to a broadcast address

### ISSUE THREAD

**Issue by nmoehrle** [pgiri/dispy#108]
As far as I could figure out windows does not allow you to bind to a broadcast address ([here](https://github.com/pgiri/dispy/blob/master/py3/dispy/__init__.py#L808), which means that I get the following error when using dispy with netifaces:
`OSError: [WinError 10049] The requested address is not valid in its context`

I think on windows you will have to bind to `addrinfo.ip` instead of `addrinfo.broadcast`, is that right?

Best wishes,

**Comment by pgiri** [comment]
I don't have access to Windows machine to test / understand. If you manage to make it work for you, let me know and may be that is the right fix?

**Comment by nmoehrle** [comment]
We have been using the patch #111 for a couple of runs now and it resolve the problem for us.
