### ISSUE TITLE
Broadcasts are no longer received on linux

### ISSUE THREAD

**Issue by nmoehrle** [pgiri/dispy#113]
With my recent patch #111 I broke the reception of broadcasts in linux an propably OS X. I will propose a fix as PR, reverting some of the changes, as fast as I can. I am sorry for the inconvenience.

**Comment by pgiri** [comment]
No problem and no hurry; next release is not planned soon.

I have been meaning to test OS X with IPv6 when I get a chance, but haven't had much time.
