### ISSUE TITLE
Error while running sample.py

### ISSUE THREAD

**Issue by vsharathchandra** [pgiri/dispy#116]
I am running the following [example](http://dispy.sourceforge.net/examples.html). I ran the sample.py. I recieved the following error

> pycos - uncaught exception in !udp_server/20697168:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pycos/__init__.py", line 3676, in _schedule
    retval = task._generator.send(task._value)
  File "/usr/lib/python2.7/site-packages/dispy/__init__.py", line 843, in udp_server
    udp_sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 22] Invalid argument

I am working on a centos 7 system.The code worked perfectly on other systems of the same configuration.

**Comment by pgiri** [comment]
I am guessing IPV6_V6ONLY attribute is missing on that system / Python? Can you try commenting out line 843 in dispy's "__init__.py" file?

**Comment by soares741** [comment]
I have the same situation

While I was running on my local system it worked but once I try to run it on the server no longer works.
In the server environment I am using virtualenv with python3.4 

Commenting the line solves the issue as suggested. Any idea when a definite fix can be available? 

Another issue I have after commenting the line:
On my dispy node I set `-i IPv4` and use the same IP on the client but doesn't work. Only works with IPv6

**Comment by pgiri** [comment]
Could you check and confirm if above fix works (or not)?

**Comment by soares741** [comment]
For me it didn't solve
when I do `print(hasattr(socket, 'IPV6_V6ONLY'))` it returns true and executes the setsockopt

My stacktrace:
```
Traceback (most recent call last):
  File "/home/data_processing/test-dispy/raw-data-reprocessing/env/lib/python3.4/site-packages/pycos/__init__.py", line 3732, in _schedule
    retval = task._generator.send(task._value)
  File "/home/data_processing/test-dispy/raw-data-reprocessing/env/lib/python3.4/site-packages/dispy/__init__.py", line 847, in udp_server
    udp_sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
OSError: [Errno 22] Invalid argument
```

**Comment by soares741** [comment]
I no longer have that error 👍 
But maybe is better if @vsharathchandra confirms it's working for him
