### ISSUE TITLE
Client not reconnecting to nodes upon restart

### ISSUE THREAD

**Issue by matthewwardrop** [pgiri/dispy#12]
Hi pgiri,

Another bug? When I kill `dispynode.py` on a server, and then restart it, it used to be that the client would redetect it and send it jobs. Now, it seems not to update the number of CPUs available; and the hostname remains in the `httpd` monitor with 0 cpus. I'll add more info if I get a chance to debug it further.

M

**Comment by pgiri** [comment]
If you upgraded to latest tree and interrupted, restarted dispynode, but not the client, then the client didn't detect the node (the protocol between them has changed in the last commit).

**Comment by matthewwardrop** [comment]
Unfortunately it is more complex than that; since both the client and server have been restarted several times. I'll see if I cannot identify the issue.

**Comment by matthewwardrop** [comment]
The issue is resolved by reverting your latest public commit: https://github.com/pgiri/dispy/commit/e9b6dacc3547b64261130452f60ba8d56de0488d . Not sure if you have unpushed commits which resolve this; but for now, I'll run with that commit reverted, and my two patches applied.

**Comment by pgiri** [comment]
I pushed all my commits. Let me know if this doesn't work for you.

**Comment by matthewwardrop** [comment]
Things appear to be working nicely again. Thanks pgiri :).
