### ISSUE TITLE
Error starting dispynode from config file with ip_addrs defined

### ISSUE THREAD

**Issue by soares741** [pgiri/dispy#120]
When I try to start my dispynode with the` --config` where I have my `ip_addrs` defined I get the following error:
```
2018-04-25 16:02:15 dispynode - dispynode version: 4.8.5, PID: 89756
Traceback (most recent call last):
  File "./env/lib/python3.6/site-packages/dispy/dispynode.py", line 1932, in <module>
    _dispy_node = _DispyNode(**_dispy_config)
  File "./env/lib/python3.6/site-packages/dispy/dispynode.py", line 239, in __init__
    if not addrinfo.ip:
AttributeError: 'NoneType' object has no attribute 'ip'
```

I have this quick fix for it: 
```
if not ip_addrs:
    ip_addrs = [None]
elif ip_addrs and type(ip_addrs) is str:
    ip_addrs = ast.literal_eval(ip_addrs)

 if not ext_ip_addrs:
    ext_ip_addrs = [None]
if ext_ip_addrs and type(ext_ip_addrs) is str:
    ext_ip_addrs = ast.literal_eval(ext_ip_addrs)
```

Let me know what you think

**Comment by soares741** [comment]
I generated the config file using the `--save_config <file>` flag and it created this file:

```
[DEFAULT]
cpus = 1
ip_addrs = ['222.222.222.222']
ext_ip_addrs = ['111.111.111.111']
loglevel = True
node_port = 51348
name = 
dest_path_prefix = 
scheduler_node = 
scheduler_port = 51347
max_file_size = 0
zombie_interval = 60.0
ping_interval = 0
service_start = 
service_stop = 
service_end = 
serve = -1
client_shutdown = False
msg_timeout = 10
secret = 
certfile = 
keyfile = 
clean = True
daemon = True
```
In the constructor it expects a list but all it receives is a string and then in the cycle `for i in range(len(ip_addrs)):` it just loops over each character and not each IP

I don't think your fix in #40f53e2 would be enough

**Comment by pgiri** [comment]
I believe patch committed should fix the issue. It was not clear to me where your proposed fix above should be at. Moreover, parsing with ast would mean importing another module, which takes up some space (taking it away from computations). Although ast's `literal_eval` is safer than `eval`, in this case, the variables should only be list of strings so it should be okay to use `eval`.

**Comment by soares741** [comment]
Thanks! 

That fix worked partially!
If in the config file its defined
```
ext_ip_addrs = []
ip_addrs = ['myIPv4]
```
I have get a warning `Ignoring invalid ext_ip_addr [`
And then the IPv4 defined in the config file is not used and it uses the server IPv6 by default

Although all works if on the config file I have 
```
ext_ip_addrs = 
ip_addrs = ['myIPv4]
```

I'm mentioning this because the default config file generated by the `--save_config`  flag is generated like this: `ext_ip_addrs = []` so for consistency would be better to solve this warning

I read those details in the documentation but I need this feature because I am deploying the Dispy module on the cluster using Ansible and creating the config for each machine at the same time. 

Thank you for going through this :)

**Comment by soares741** [comment]
Looks good to me!! 
You can close this ticket! 
Just one question, when can you make a release with all the latest changes?

**Comment by pgiri** [comment]
I have couple of patches pending. I will commit them over the weekend and planing to release new version early next week.

**Comment by soares741** [comment]
Sweet! 
That would be great thanks 👍
