### ISSUE TITLE
Cannot start cluster after recovering jobs

### ISSUE THREAD

**Issue by nmoehrle** [pgiri/dispy#125]
I am unable to start a cluster after recovering jobs, the app hangs in [`dispy.JobCluster.__init__()`](https://github.com/pgiri/dispy/blob/master/py3/dispy/__init__.py#L2478) on [pycos.Task.value()`](https://github.com/pgiri/pycos/blob/master/py3/pycos/__init__.py#L2688) it seams like the scheduler waits for the notifier indefinitely. Could there be an issue with the notifier when pycos has been terminated already once?

**Comment by pgiri** [comment]
I assume you mean `add_cluster`task is hanging? I am guessing that `recover_jobs` didn't get all the jobs so it didn't close the nodes. In that case, the nodes that were used in previous computation will not respond to new cluster until previous computation is closed (either through `recover_jobs` or zombie period elapses).

Can you check on dispynode's command line to see if node is not being used by other (previous) computation? If it runs as daemon, you can check process list and look for Python programs.

And if it is possible to reproduce this issue, let me know steps / sample program.

**Comment by nmoehrle** [comment]
Yes the `add_cluster` is hanging however how is that related to nodes that are "hanging" in another computation? To my understanding they should just not respond, but not interfere with the cluster initialization. To me it seams like the pycos Task containing the add_cluster call is never scheduled.

**Comment by nmoehrle** [comment]
When inspecting the deadlock with pdb it appears that the `Pycos._schedule` function is polling on a `pycos._AsyncPoller` that is different from the `pycos.Task._pycos._notifier`. Infact it seams as if there are two Pycos objects, which might be caused by the use of [`Pycos()`](https://github.com/pgiri/dispy/blob/master/py3/dispy/__init__.py#L697). However I don't get why there would only be one thread executing `_schedule()`.
```
(Pdb) import sys, traceback
(Pdb) from functools import reduce
(Pdb) for id, frame in sys._current_frames().items(): print(id); print('\n'.join(map(str, traceback.extract_stack(frame)))); print()
139898871486208
<FrameSummary file /usr/lib/python3.6/threading.py, line 884 in _bootstrap>
<FrameSummary file /usr/lib/python3.6/threading.py, line 916 in _bootstrap_inner>
<FrameSummary file /usr/lib/python3.6/threading.py, line 864 in run>
<FrameSummary file /usr/local/lib/python3.6/dist-packages/dispy/__init__.py, line 1643 in worker>
<FrameSummary file /usr/lib/python3.6/queue.py, line 164 in get>
<FrameSummary file /usr/lib/python3.6/threading.py, line 295 in wait>

139898894726912
<FrameSummary file /usr/lib/python3.6/threading.py, line 884 in _bootstrap>
<FrameSummary file /usr/lib/python3.6/threading.py, line 916 in _bootstrap_inner>
<FrameSummary file /usr/lib/python3.6/threading.py, line 864 in run>
<FrameSummary file /usr/local/lib/python3.6/dist-packages/pycos/__init__.py, line 3695 in _schedule>
<FrameSummary file /usr/local/lib/python3.6/dist-packages/pycos/__init__.py, line 1826 in poll>

139898953353024
<FrameSummary file /usr/lib/python3.6/runpy.py, line 193 in _run_module_as_main>
<FrameSummary file /usr/lib/python3.6/runpy.py, line 85 in _run_code>
<FrameSummary file /usr/lib/python3.6/pdb.py, line 1694 in <module>>
<FrameSummary file /usr/lib/python3.6/pdb.py, line 1667 in main>
<FrameSummary file /usr/lib/python3.6/pdb.py, line 1548 in _runscript>
<FrameSummary file /usr/lib/python3.6/bdb.py, line 434 in run>
<FrameSummary (Pdb) file <string>, line 1 in <module>>
<FrameSummary file /home/nmoehrle/repos/test/master.py, line 1 in <module>>
<FrameSummary file /usr/local/lib/python3.6/dist-packages/dispy/__init__.py, line 2478 in __init__>
<FrameSummary file /usr/local/lib/python3.6/dist-packages/pycos/__init__.py, line 2688 in value>
<FrameSummary file /usr/lib/python3.6/threading.py, line 551 in wait>
<FrameSummary file /usr/lib/python3.6/threading.py, line 295 in wait>
<FrameSummary file /usr/lib/python3.6/pdb.py, line 188 in sigint_handler>
<FrameSummary file /usr/lib/python3.6/bdb.py, line 53 in trace_dispatch>
<FrameSummary file /usr/lib/python3.6/bdb.py, line 85 in dispatch_call>
<FrameSummary file /usr/lib/python3.6/pdb.py, line 251 in user_call>
<FrameSummary file /usr/lib/python3.6/pdb.py, line 352 in interaction>
<FrameSummary file /usr/lib/python3.6/pdb.py, line 321 in _cmdloop>
<FrameSummary file /usr/lib/python3.6/cmd.py, line 138 in cmdloop>
<FrameSummary file /usr/lib/python3.6/pdb.py, line 418 in onecmd>
<FrameSummary file /usr/lib/python3.6/cmd.py, line 216 in onecmd>
<FrameSummary file /usr/lib/python3.6/pdb.py, line 376 in default>
<FrameSummary file <stdin>, line 1 in <module>>

(Pdb) sys._current_frames()[139898894726912].f_locals
{'poll_timeout': -1, 'timeout': None, 'self': <pycos._AsyncPoller object at 0x7f3cbfee3048>}
(Pdb) reduce(lambda frame, n: frame.f_back, range(13), sys._current_frames()[139898953353024]).f_locals['self']._pycos._notifier
<pycos._AsyncPoller object at 0x7f3cc1436f98>
(Pdb) id(reduce(lambda frame, n: frame.f_back, range(13), sys._current_frames()[139898953353024]).f_locals['self']._pycos)
139898917130424
(Pdb) id(sys._current_frames()[139898894726912].f_back.f_locals['self'])
139898894825064
```

**Comment by nmoehrle** [comment]
Oh the `reduce(lambda frame, n: frame.f_back, range(13), ...)` simply moves up 13 stack frames.
Sorry that is a little ugly...

**Comment by nmoehrle** [comment]
I think I got it: the scheduler for the tasks (`Task._pycos`) is not reset to `None` when `Pycos._schedule()` exits due to the [`Pycos.instance().finish()`](https://github.com/pgiri/dispy/blob/master/py3/dispy/__init__.py#L3358) call in `recover_jobs`. This means that any new tasks will still register to the `Pycos` instance that has already quit.

**Comment by nmoehrle** [comment]
The referenced PRs solve the issue for me :-) Note that I did not check for similar issues in other parts - without an in depth knowledge or a concrete issue judging this is quite hard...
