### ISSUE TITLE
http server takes too long to shut down

### ISSUE THREAD

**Issue by matthewwardrop** [pgiri/dispy#13]
Running sequential tasks using dispy with http is currently not possible (at least on my machines) because the http server takes too long to shut down; resulting in the error:

`socket.error: [Errno 98] Address already in use`

Is it possible to detect when the socket has been freed, and wait until then to return from the `shutdown` method?

**Comment by matthewwardrop** [comment]
Closing in favour of my pull request.

**Comment by pgiri** [comment]
I pulled this patch, but looking through, I am wondering if it would be better to close socket after the server was shutdown; i.e., move the two lines one to right after 'self._server.shutdown()'.I don't know if now / later, HTTPServer shutdown would expect the socket to be alive and use it and/or not shutdown properly. I assumed shutting down server would close socket. Can you test if it works?

**Comment by pgiri** [comment]
Yet another comment on this: Looking through SocketServer, it seems after 'self._server.shutdown()', calling 'self._server.server_close()' in httpd.py should close the socket (instead of 'self._server.socket.close()'). I have not been able to reproduce your issue, so I don't know if this works. If it works, it may be better approach.

**Comment by matthewwardrop** [comment]
Yeah... I wasn't too sure about this. I quickly looked through the
documentation, and settled on this as a hotfix. I'll see if the neater
solution you proposed works, or if not, see how best to do it... And then
send another pull request. Thanks for mainlining it.

**Comment by matthewwardrop** [comment]
So `server_close` is undocumented. As such, I'd feel a little uneasy recommending its use; as that could change without notice. I put the two lines before shutdown just in case the shutdown process changed the available attributes of the SocketServer; but I think you're right, moving them afterward is safer. I've tested it (it works), and submitted a pull request for it.
