### ISSUE TITLE
How to print from compute() onto remote node terminal running dispynode?

### ISSUE THREAD

**Issue by Kekushke** [pgiri/dispy#131]
Quick question... On the remote nodes `stdout` and `sterr` gets re-directed, however, I would like to dump output of `print` statements in `compute()`  onto remote terminal window running`dispynode -d` during development/debug. Is there an easy way to do that...? Alternate method to `print` to print on node terminal will also help. May be there is something already in `dispy` that I am unaware of. Thank you!

**Comment by pgiri** [comment]
`_dispy_logger` can be used similar to print function, e.g., as `_dispy_logger.info("n = %s" % n)`.

**Comment by Kekushke** [comment]
@pgiri  Thank you for the note.
