### ISSUE TITLE
Asynchronous messages possibly seeing Race Condition... How to solve this?

### ISSUE THREAD

**Issue by Kekushke** [pgiri/dispy#132]
In a particular use case we have, node `compute() ` is running an asynchronous process and relays messages asynchronously  via `dispy_provisional_result()`. Upon receiving message client does some post processing  in client `callback()` by looking at  `job.status == dispy.DispyJob.ProvisionalResult`. The ` callback()`  is also able to process particular code if  `job.status == dispy.DispyJob.Finished`. However, while processing the code related to finished job, we see that the callback gets re- instantiated by pending or later arriving `dispy_provisional_result()`. This causes it to execute job finished code multiple times. Any way to prevent this? I am guessing a good switch combinations  job status checks should prevent that.... but not sure how.

**Comment by Kekushke** [comment]
Thought I can ask this question in yet another way.  I think what we are looking for is separate callbacks for provisional messages and job finished, each. Furthermore, callback related provisional messages should no more execute if job is finished. For sure this can be accomplished in single callback(), but not sure how exactly all available `dispy.DispyJob.* ` elements could be laid out.

**Comment by pgiri** [comment]
You can perhaps use `job.id` to realize a job is finished (e.g., set it to unique value when it is submitted and clear it when callback is called with "Finished", ignore it if id is already cleared).

**Comment by Kekushke** [comment]
@pgiri Yes, that would definitely work. Thank you for the note. Just to let you know, `dispy` is working really well for us on a very large compute farm. As long as API's are kept simple and clean as they are, this project is going have a life of several decades and beyond. Awesome work @pgiri!

**Comment by pgiri** [comment]
I am interested to know where / what project are you using it for. If you prefer, you can email me instead.

**Comment by Kekushke** [comment]
So far we have used it for three distinct and large engineering optimization problems. In each one of these, we were able to integrate `dispy` most effortlessly compared to many other solutions we have used in the past.

**Comment by pgiri** [comment]
Thank you very much for your comments!

**Comment by pgiri** [comment]
It later occurred to me that the scenario you encountered is not supposed to happen (well, technically possible but should be rare): See the comment in dispy's `__init__.py` file for DispyJob. dispy should run callback for provisional result ahead of finished as they are sorted in the queue. There is still a possibility to call them in out-of-order if replies from node arrive at the client out-of-order (due to two separate sockets sending data to client).

While you handled the situation at the client, I am wondering if the issue is something else or indeed it is rare occurrence.

**Comment by Kekushke** [comment]
Just another thought. Actually it will be great if callback for end of the jobs are different than those for the provisional results. It will be cleaner design I think! :-)  However, I will report on what I see as soon as I find more.
