### ISSUE TITLE
Sample.py does not run to completion (and neither do other projects using dispy)

### ISSUE THREAD

**Issue by shadowclan98** [pgiri/dispy#133]
I decided to run sample.py to see if dispy was working properly for a different project that uses dispy. However, I find that sample.py does not run to completion. (Neither does the original project I was testing.) In all instances, I have had to Ctrl-Z and kill the python process. Displaying the job.status shows that the jobs are created, but do not finish.
The following is the output I get from running `sample.py`
`2018-06-19 11:22:45 pycos - version 4.6.6 with epoll I/O notifier`  
`2018-06-19 11:22:45 dispy - dispy client version: 4.8.7`
`2018-06-19 11:22:45 dispy - Storing fault recovery information in "_dispy_20180619112245"`
I am not sure what is causing this problem.

The same occurs when I run a simple program modeled after `sample.py`
`def sum(a,b):`
`        return a+b`
`if ___name___ == '___main___':`
`        import dispy`
`        cluster = dispy.JobCluster(sum,cleanup=True,pulse_interval=5,loglevel=dispy.logger.DEBUG)`
`        jobs = []`
`        for i in range(1):`
`                job = cluster.submit(i,i+1)`
`                job.id = i`
`                jobs.append(job)`
`                print(job.status)`
`        #jobs = dispy.recover_jobs(timeout=1,terminate_pending=True)`
`        for job in jobs:`
`                print(job.status)`
`                sums = job()`
`                print sums`
`        cluster.print_status()`

**Comment by shadowclan98** [comment]
When running the original more complex project with some debugging optional arguments added to server side, I get the following as my last output: 
![image](https://user-images.githubusercontent.com/20131316/41613381-6a64740a-73c3-11e8-947d-92025460a9e6.png)

**Comment by shadowclan98** [comment]
To clarify, the previous image is the output that includes the following:
`pulse_interval=5,ping_interval=5,loglevel=dispy.logger.DEBUG)` in JobCluster
`-d --zombie_interval=5 --serve 1 --clean --dest_path_prefix dispytmp_' + str(i)` for running dispynode.py in a subprocess under the same machine after another ssh.

**Comment by pgiri** [comment]
That image doesn't show output from dispynode. It seems either there are network issues (client and node not able to communicate) or setup of node failed (dispynode output may indicate why).

**Comment by shadowclan98** [comment]
If I just run dispynode.py with -d, I get:
![image](https://user-images.githubusercontent.com/20131316/41615391-1fec8d44-73c9-11e8-873f-f4c8200c7ddb.png)

**Comment by pgiri** [comment]
Probably there is another dispynode running? Check processes, kill all dispynode processes and restart dispynode with '--clean' option.

**Comment by shadowclan98** [comment]
When checking the processes, there are no other dispynode processes running. And restarting dispynode.py gives the same output. Each time I stop the python program, I make sure to kill the processes associated to it (usually just the one process, python). 
Note: I am setting the client and server as the same machine (in workspace accessed via ssh). From reading other issues, I am not sure if this is caused by the firewall, but I did set my personal machine to allow the default ports.

**Comment by shadowclan98** [comment]
It seems that there are processes that are being shown when I use that command. However, since I do not have root access, I am not able to see what specific programs are using 51348 aside from the ones that I was running [i.e. python before I fully kill it]. The image shows the output of the above command after I kill python.
![image](https://user-images.githubusercontent.com/20131316/41680535-c98c8666-749f-11e8-9c37-683bb8781e60.png)

**Comment by pgiri** [comment]
You can start dispynode on a different port (e.g., 5555) and then pass `node_port=5555` to `JobCluster`.

**Comment by shadowclan98** [comment]
Killing the processes on the port 51348 did help dispy/dispytuner make the connection. Thank you.
