### ISSUE TITLE
"Could not send reply for job"

### ISSUE THREAD

**Issue by gobbedy** [pgiri/dispy#136]
Hi again,

First off thanks so much for your help with the other issues I opened. So far I'm pleased with my trial of dispy.

I've tried the example code (with small changes) on several pairs of nodes, and it has worked without problem.

Until at some point on one pair of nodes after killing dispynode.py and relaunching it with --clean, I got a bunch of messages like this on the server node:

> 2018-07-18 16:37:27 dispynode - Could not send reply for job 140115792197096 to ('172.16.142.49', 51347); saving it in "/tmp/dispy/node/172.16.142.49/my_test_function_3azb4shn/_dispy_job_reply_140115792197096"
> 2018-07-18 16:37:27 dispynode - Could not send reply for job 140115792087104 to ('172.16.142.49', 51347); saving it in "/tmp/dispy/node/172.16.142.49/my_test_function_3azb4shn/_dispy_job_reply_140115792087104"

And on the client node, messages like this:  

> 2018-07-18 16:38:22 dispy - Ignoring invalid reply for job 140115792085064 from 172.16.142.50
> 2018-07-18 16:38:22 dispy - Ignoring invalid reply for job 140115792085064 from 172.16.142.50
> 2018-07-18 16:38:22 dispy - Ignoring invalid reply for job 140115792085064 from 172.16.142.50
> 2018-07-18 16:38:22 dispy - Ignoring invalid reply for job 140115792085064 from 172.16.142.50

I have a gut feeling it somehow means the previous dispynode was not killed properly, but I have no idea how to debug.

Could you please provide guidance?

**Comment by pgiri** [comment]
If you start dispynode with `--clean` option, the node discards any pending job results saved and it shouldn't cause "Could not send reply for job" errors on the node.

The scheduler ignores any reply for a job that it discarded (e.g., after a node is deemed zombie), which is what you are seeing at the client. There are a few options. You can use `reentrant=True` parameter to JobCluster if your computation is reentrant. In that case, the scheduler will resubmit any failed jobs to new nodes found and will finish all jobs. Another option is to use `recover_jobs` function to get results for any jobs finished at the node but not received by client (although from your description it looks like this case doesn't apply).

If the nodes can be killed before jobs are done, there is not much that can be done to cleanly finish them all, except if computation is reentrant. Then as I suggested, each time, start dispynode with `--clean` and use `reentrant=True` to JobCluster. See documentation for more details.

**Comment by gobbedy** [comment]
@pgiri thanks as always for your fast reply.

Unfortunately I've been using the --clean option, but the "Could not send reply" are in spite of it.

This is the exact command I've been using:
`dispynode.py --clean --daemon &`

If I'm not mistaken, the rest of your message pertains to the client side messages ("Ignoring invalid replies"), which I think will be fixed when the server works properly. I do appreciate the explanation and it caused me to google reentrancy, so I learned something. I don't believe my computation is re-entrant.

Lastly, to clarify, there were no jobs running when the nodes were killed. The only thing running was the dispynode script itself.

At the point I'll speak to the sysadmin to find out if there's anything I can do (some kind of reboot or simulated reboot before every session perhaps)

**Comment by gobbedy** [comment]
I have been avoiding backgrounding the script.

In other words instead of
`dispynode.py --clean --daemon &`

I do `dispynode.py --clean --daemon`

To effectively background the script  I launch it inside tmux.

For reasons I don't understand, the issue I was seeing does not occur when the script is run in the foreground. I can use the same node at will and there seems to be no recovery problem.

Closing as I have a workaround.
