### ISSUE TITLE
help with transferring an object via setup

### ISSUE THREAD

**Issue by gobbedy** [pgiri/dispy#138]
Hello,

I'm attempting to use the setup function to distribute arrays to my remote nodes. Instead of sending variable via a file as per the example, is it possible to pass an object?

I've tried to do it but I get this error: "2018-08-16 06:30:56 dispy - Failed to setup <ip address> for compute "compute": -1"

Below is my example code.

Could you guide me as to what I did wrong? (Assuming that what I'm trying to do is even supported)

Thanks in advance!

```python

import random, dispy, functools

class my_setup_class:
    def __init__(self, a, b):
        self.a = a
        self.b = b

def setup(my_setup_obj):
    global x, y
    x = my_setup_obj.a
    y = my_setup_obj.b

class C(object):
    def __init__(self, n):
        self.n = n

    def show(self):
        print('%s: %.2f' % (self.i, self.n))

    def compute(self):
        # obj is an instance of C
        import time
        time.sleep(self.n)
        self.show()  # the output is stored in job.stdout
        print(x) # do something with x
        print(y) # do something with y
        return self.n

    def distribute(self):

        my_setup_obj = my_setup_class(2,3)
        cluster = dispy.JobCluster(self.compute, depends=[C, my_setup_obj], nodes=['node1',], setup=functools.partial(setup, my_setup_obj))
        jobs = []
        for i in range(10):
            self.i = i
            job = cluster.submit(self) # it is sent to a node for executing 'compute'
            job.id = i # store this object for later use
            jobs.append(job)
        for job in jobs:
            job() # wait for job to finish
            print('%s: %.2f / %s' % (job.id, job.result, job.stdout))

if __name__ == '__main__':
    c = C(random.uniform(1, 3)) # create object of C
    c.distribute()

```

**Comment by pgiri** [comment]
Using `setup` with objects is the problem here. When computation is sent to node, it is serialized. At the node when deserializing, all definitions must already be known. In this case, `my_setup_obj` requires `my_setup_class` to be available at the node already, but is not (it is sent along with `my_setup_obj`, but which order the interpreter chooses to process is not defined).

Below program works. Note that `setup` must return 0 to indicate success. I replaced `print` in `show` to `_dispy_logger.info` which will print at the node, whereas `print` will buffer the output and sent to client as `job.stdout`.

    import random, dispy, functools

    class my_setup_class(object):
        def __init__(self, a, b):
            self.a = a
            self.b = b

    def setup(a, b):
        global x, y
        x = a
        y = b
        return 0

    class C(object):
        def __init__(self, n):
            self.n = n

        def show(self):
            _dispy_logger.info('%s: %.2f' % (self.i, self.n))

        def compute(self):
            # obj is an instance of C
            _dispy_logger.info('x: %s, y: %s', x, y) # do something with x
            self.show()
            import time
            time.sleep(self.n)
            self.show()  # the output is stored in job.stdout
            return self.n

        def distribute(self):

            # my_setup_obj = my_setup_class(2,3)
            #my_setup_obj.a = 2 # computed on the fly
            #my_setup_obj.b = 3 # computed on the fly
            cluster = dispy.JobCluster(self.compute, depends=[C, my_setup_class],
                                       setup=functools.partial(setup, 2, 3))
            jobs = []
            for i in range(2):
                self.i = i
                job = cluster.submit(self) # it is sent to a node for executing 'compute'
                job.id = i # store this object for later use
                jobs.append(job)
            for job in jobs:
                job() # wait for job to finish
                if job.status == dispy.DispyJob.Finished:
                    print('%s: %.2f / %s' % (job.id, job.result, job.stdout))
                else:
                    print('%s: %s / %s, %s' % (job.id, job.stderr, job.stdout, job.exception))

    if __name__ == '__main__':
        c = C(random.uniform(1, 3)) # create object of C
        c.distribute()

**Comment by gobbedy** [comment]
Thank you @pgiri . Since I couldn't send across an object, I dumped it to a file and sent across the file as per the origtnal example. I was hoping that sending the object itself would be more efficient than doing I/O, but this seems to work alright speedwise.
I did try to do what you suggest via your example (ie send across the individual members) but the individual members are large arrays. Admittedly I can't remember why it didn't work, but I hit some other issue there.
Again I'd like to commend you on dispy, I spent a long term researching python options for distributed computing on clusters and dispy is by far the most complete solution (features + documentation + actively maintained + supported). Well done!
PS. Thanks for informing me about dispy_logger, useful to know.

**Comment by pgiri** [comment]
Thanks for your comments about dispy.

Sending large amount of data would usually be more efficient with files instead of objects (I think), as serializing data is avoided, and transfer of files is done with asynchronous, concurrent I/O (same as for large objects). It is also possible to partition data (dynamically, with `NodeAllocate` objects as `nodes`) and send each part to a node that processes that data.
