### ISSUE TITLE
importing torch in setup causes runtime error

### ISSUE THREAD

**Issue by gobbedy** [pgiri/dispy#143]
Hello,

When a setup function imports torch, the second loading of the setup function will fail with a runtime error.

Here is the error:

> 2018-08-30 18:39:43 dispy - Setup of computation "compute" on 206.12.124.2 failed: bytearray(b'Traceback (most recent call last):\n  File "/home/gobbedy/.local/bin/dispynode.py", line 880, in setup_computation\n    compute.setup.name, globalvars, localvars)\n  File "<string>", line 1, in <module>\n  File "<string>", line 7, in setup\n  File "/home/gobbedy/.local/lib/python3.6/site-packages/torch/__init__.py", line 184, in <module>\n    from .tensor import Tensor\n  File "/home/gobbedy/.local/lib/python3.6/site-packages/torch/tensor.py", line 12, in <module>\n    class Tensor(torch._C._TensorBase):\n  File "/home/gobbedy/.local/lib/python3.6/site-packages/torch/tensor.py", line 170, in Tensor\n    """)\nRuntimeError: method \'detach\' already has a docstring\n')
> 2018-08-30 18:39:43 dispy - Failed to setup 206.12.124.2 for compute "compute": bytearray(b'Traceback (most recent call last):\n  File "/home/gobbedy/.local/bin/dispynode.py", line 880, in setup_computation\n    compute.setup.name, globalvars, localvars)\n  File "<string>", line 1, in <module>\n  File "<string>", line 7, in setup\n  File "/home/gobbedy/.local/lib/python3.6/site-packages/torch/__init__.py", line 184, in <module>\n    from .tensor import Tensor\n  File "/home/gobbedy/.local/lib/python3.6/site-packages/torch/tensor.py", line 12, in <module>\n    class Tensor(torch._C._TensorBase):\n  File "/home/gobbedy/.local/lib/python3.6/site-packages/torch/tensor.py", line 170, in Tensor\n    """)\nRuntimeError: method \'detach\' already has a docstring\n')

This is rather difficult to read, so for readability I point you to the following issue whose traceback is similar: https://github.com/spyder-ide/spyder/issues/7041

To reproduce, simply run the standalone below. The error occurs upon the second call to `run_jobs()`, which in turn sets up `setup()` on the remote server for the second time.

```python
import dispy

def setup():
    import torch
    # do something
    return 0


def compute(n):
    # do something
    return n

def run_jobs():

    cluster = dispy.JobCluster(compute, setup=setup, nodes=['remote_node'])

    jobs = []
    for n in range(10):
        job = cluster.submit(n)
        job.id = n
        jobs.append(job)

    for job in jobs:
        job()
        if job.status == dispy.DispyJob.Finished:
            print('%s: %s' % (job.id, job.result))
        else:
            print(job.exception)
    cluster.print_status()

    cluster.close()

if __name__ == '__main__':
    run_jobs()
    run_jobs() # error occurs when setup called second time
```

Note that I can move the torch-related code to the compute function without error. However this causes a >10x slowdown in my real code, so this is not a viable option.

For me this is a blocking issue. :(

**Comment by pgiri** [comment]
dispynode unloads modules loaded by computation when that computation is finished. However, 'torch' module seems to have side effects that affect it when it is reloaded by new computation. You have two choices: Use virtualization and restart dispynode for each client (see [dispynode Containers](http://dispy.sourceforge.net/dispynode.html#containers), especially on how to run each client in a separate container), or use pycos (with dispycos module).  dispycos runs each client in separate process so one client's side effects are not affected by another client. Attached is simple program that loads 'torch' module in dispycos:

```python
import pycos.netpycos as pycos
from pycos.dispycos import *


def compute(i, n, task=None):
    yield task.sleep(n)
    raise StopIteration((i, task.location, torch.__version__))

def client_proc(computation, njobs, task=None):
    if (yield computation.schedule()):
        raise Exception('Could not schedule computation')

    args = [(i, random.uniform(1, 3)) for i in range(njobs)]
    results = yield computation.run_results(compute, args)
    for result in results:
        print('    result for %d from %s: %s' % result)

    # wait for all jobs to be done and close computation
    yield computation.close()


def node_setup(task=None):
    global torch
    import torch
    yield 0

if __name__ == '__main__':
    import random, sys, pycos.dispycos
    Scheduler()
    computation = Computation([compute], node_setup=node_setup)
    pycos.Task(client_proc, computation, 2 if len(sys.argv) < 2 else int(sys.argv[1])).value()
```

**Comment by gobbedy** [comment]
Thanks @pgiri 
I did try to relaunch dispynode on each node but it took several seconds and since I needed to 100,000 calls to a new node_setup, this was not feasible

I also try dispycos, but I ran into a different issue. I opened an issue regarding this issue, see https://github.com/pgiri/pycos/issues/8

**Comment by pgiri** [comment]
What OS do you use on the nodes? I have done some reworking of dispynode to run setup in separate process per client (similar to dispycos). However, this is not ready yet and not tested in Windows. If you use Linux / BSD variants, I can finish this in the next couple of days and send it for testing.

**Comment by pgiri** [comment]
pycos / dispycos offers a different computational model (as mentioned in [pycos issue 8](https://github.com/pgiri/pycos/issues/8)) that is more generic than the one possible with dispy. Essentially with dispycos, you can setup each CPU on a node as an independently addressable,  asynchronous communicating  computing processor to not just compute one fixed method (as done with dispy), but also to continually altering / evolving model (since servers accept any computation to be run at any time in the same process until computation is closed).

**Comment by pgiri** [comment]
Email me if you want to use dispy with changes mentioned above, so I can send you new version. Let me also know if you use Python 2.7+ or Python 3+.

**Comment by gobbedy** [comment]
@pgiri I sent you an e-mail at pgiri@yahoo.com, hopefully you received it!

**Comment by pgiri** [comment]
I have sent you new package to test last week, as well as just now. Let me know if you haven't received it.

**Comment by gobbedy** [comment]
Oh, strange. I have no e-mails from you (neither last week nor now..)

Was there an attachment? Perhaps my university's firewall blocked it...

Can you try this e-mail instead?
guigui.the.bulldozer@gmail.com

**Comment by pgiri** [comment]
Forwarded the email to new address.

**Comment by pgiri** [comment]
Hmm, email to new address bounced due to security concerns (contains package). Likely same issue with the other address as well?

**Comment by gobbedy** [comment]
Ah yes probably. The other one probably just bounced it silently..

Perhaps you could share it via google drive or a github repo?

**Comment by gobbedy** [comment]
I tried with the example in the original comment and it worked. So far so good! Next I'll try with my real code.

**Comment by pgiri** [comment]
Great!

Note that importing "torch" module to computation slows down because this is rather large module so loading takes time, and each job executes in a separate process so it takes multiple times (as many jobs that can run simultaneously, which is number of processors) space (memory) which may cause thrashing. Loading it in "setup" with non-Windows systems will load the module once but is available to all jobs.

**Comment by gobbedy** [comment]
It works. Wouhou! You sir are the man.

**Comment by gobbedy** [comment]
And ya about the loading of torch in every compute, that makes a lot of sense.

Oh I've been wondering, is there a way to get dispy to use local cores without launching a dispynode? Probably not, but just wondering since I imagine it'd be a bit faster (my launch node has 48 cores)..

**Comment by pgiri** [comment]
If client (launch node) can also be used for computation, then just run dispynode on it as well. dispy will only use a node that runs dispynode.

**Comment by gobbedy** [comment]
That makes sense. Thank you.
