### ISSUE TITLE
discover new node and schedule job on the new node after Client started 

### ISSUE THREAD

**Issue by 7starsea** [pgiri/dispy#144]
Can dispy-client discover new node after client has started?
My use case is that dispy-client start on a node before dispynode starts on a new node.

Thanks.
Aimin

**Comment by pgiri** [comment]
Yes, client can detect new nodes, provided firewall doesn't prevent UDP (used for broadcasting) and UDP is not lossy (which is more common with wifi).

**Comment by 7starsea** [comment]
I tested and client can detect new nodes. Thanks.
