### ISSUE TITLE
Problems about in-memory-processing

### ISSUE THREAD

**Issue by hcz28** [pgiri/dispy#149]
I'm following the example script in https://pgiri.github.io/dispy/examples.html#in-memory-processing, and I have two problems.
1. I understand that in **one node**, dispy can share memory on multiple processes. But what if I have multiple nodes? 
2. I have encountered one problem about pickle: `2018-09-15 16:12:07 dispy - Ignoring node 192.168.2.70: unsupported pickle protocol: 4`. The python version is 2.7.12, so how to fix this problem?
Thanks!

**Comment by hcz28** [comment]
Problem solved. It seems that dispy will load data from each node and share memory on each node. The second problem results from the python version difference between the client and server node.

**Comment by pgiri** [comment]
That is correct: The setup function that runs on a node can load data in global variables in to that node's memory. If you need to load different parts of data across all nodes, you can partition data (you can use `NodeAllocate` to get node's available memory / disk / CPUs etc to partition data dynamically) and then send parts to nodes with `depends` so appropriate part is loaded in a node's memory.

**Comment by hcz28** [comment]
@pgiri thanks
