### ISSUE TITLE
'invalid message' with dispy_provisional_result()

### ISSUE THREAD

**Issue by kernel-sanders** [pgiri/dispy#16]
I seems that dispy_provisional_result() is broken in 4.2. I used the example in the documentation and it fails, giving the error 'invalid message from x.x.x.x'. From my reading of the source, there is no header being sent with the provisional result message so the scheduler cannot determine how to handle it?

**Comment by pgiri** [comment]
Thank you very much for pointing it out (I was about to release 4.3). This will be fixed before 4.3 release.

**Comment by pgiri** [comment]
This has been fixed and 4.3 has been released!
