### ISSUE TITLE
OMP issue

### ISSUE THREAD

**Issue by gobbedy** [pgiri/dispy#160]
Hi @pgiri, I hope you're well.

I keep getting this message from my dispynode.py

OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint: Try decreasing the value of OMP_NUM_THREADS.

I've made sure that my compute jobs set OMP_NUM_THREADS=1 before doing their pytorch operations (pytorch uses OMP_NUM_THREADS to ).

So I don't understand why this is would happen. This is causing my simulation to hang.

Any idea?

**Comment by gobbedy** [comment]
I think I may have solved it. Don't waste your time with this issue just yet! Will confirm or close as the case maybe once I run a few more simulations.

**Comment by pgiri** [comment]
I am wondering why you are using both OpenMP and dispy in same application. Is OpenMP required by other dependencies?

**Comment by gobbedy** [comment]
I'm not using OpenMP.. I assumed that this was used by dispy.

I'm launching my jobs using SLURM, maybe it uses openMP to schedule jobs? I really have no idea since I know nothing about OpenMP..

**Comment by pgiri** [comment]
Hmm, actually SLURM is also not needed by dispy, so unless you have other reasons to use SLURM, you may want to consider job submission with dispy directly?

**Comment by gobbedy** [comment]
SLURM is necessary. I use a cluster shared amongst many users. Our jobs must be submitted via SLURM. SLURM is the scheduler that assigns nodes that the user (aka me) requests based on that user's priority level (in term determined by past usage relative to user's resource allocation).

Anyway these are all details but SLURM is required in my case. I request, say 10 nodes, each with 80 cores, for a total of 800 cores. My script gets launched on one of those nodes (the 'master' node). From this point is where I launch dispynode on the all of the allocated notes and use dispy to dispatch jobs from within my python script.

**Comment by gobbedy** [comment]
By setting OMP_NUM_THREADS=1 in setup, I no longer have the problem. When I did it in the compute methods, it wasn't working. Problem solved!
