### ISSUE TITLE
Injecting Python objects into namespace on server vs partial functions

### ISSUE THREAD

**Issue by matthewwardrop** [pgiri/dispy#17]
Hi pgiri,

Although we've discussed this to death, I still cannot help but feel that it is a useful feature for clarity and conciseness. Compare what would be equivalent between using partial functions and direct injection.

Partial functions:

```
import functools
def setup(custom_greeting):
    global greeting
    greeting = custom_greeting

JobCluster(...., setup=functools.partial(setup,object.custom_greeting), ...)
```

Direct injection:

```
JobCluster(..., globals={'greeting': object.custom_greeting}, ...)
```

I just cannot help but feel that reducing boilerplate is a good thing (TM). Especially since using partial functions does not increase the amount of things that can be done (pre-sent objects still need to be pickleable; it just masks this).

In my mind, `setup` should be used for computationally intensive tasks, which you do not want to pre-run on the client; or in cases where the resulting objects are not pickleable. `globals` (or some equivalent, such as `context`) should be used where you are sending simple toggles or basic data structures.

Consider this as one last plea to include direct injection upstream. If you're still not keen,  I totally understand.... I just truly think it helps rather than hinders dispy :).

Best,
M

**Comment by pgiri** [comment]
Closing this as discussed in earlier issue - "injecting" code is not intuitive and current `setup` feature seems adequate.
