### ISSUE TITLE
Reusing specified directory structure on nodes?

### ISSUE THREAD

**Issue by max810** [pgiri/dispy#171]
Is it possible to specify a concrete directory structure/path to be used on node to store files received from `depends` or `via dispy_send_file`?
The case is - we have a large dataset and we would like all the computations and jobs to reuse it - and still have the possibility to update it from time to time via `dispy_send_file` - but it looks like the node always creates something like \<dir with dispynode.py\>/dispy/node/\<some ip\>/\<some id\>/...

What I would like to see is the possibility to send all the files (from `depends` and `dispy_send_file`) to just the directory where the dispynode.py is located and launched. 
Is it possibile with the use of with cleanup and/or dest_path_prefix?

**Comment by pgiri** [comment]
You can use `dest_path` and 'cleanup=False` parameters to `JobCluster` to keep files. For example, `cluster = JobCluster(compute, dest_path="persist", cleanup=False)` will create `persist` under node's `dest_path_prefix` (which doesn't need to be changed, unless required to keep files elsewhere from default) and copy files only if not under `dest_path_prefix/persist` (or not same). After computation is done, "persist" is left behind. Next computation can then reuse those files already transferred.

Files are compared only with file size and modification time to check if file is same. That is, when files are transferred, these two attributes on client should match those on the node so files are not transferred. This should work in most cases (I think); I am not sure if there may be issues with different platforms (e.g., client is Windows, node is Linux).

**Comment by max810** [comment]
Thanks for the quick reply.
I understood how I can use `dest_path_prefix`, `dest_path` and `cleanup=False` to reuse the direcctory created for computation - and in fact it works almost perfectly - but not as i would like it to.

I create the cluster like this:
![image](https://user-images.githubusercontent.com/29955120/52775428-5f876c80-3048-11e9-976b-1df500cec74a.png)

I launch the node like this:
![image](https://user-images.githubusercontent.com/29955120/52775676-e3d9ef80-3048-11e9-8357-06443cb8c4fa.png)

And i expect my path on node for receiveing files to be _\<path to dispynode.py file\>/prefix/comp_test_

But what I received is _\<path to dispynode.py file\>/prefix/\<some ip-addr?\>/comp_test_
![image](https://user-images.githubusercontent.com/29955120/52776098-aa55b400-3049-11e9-8c00-f4d11df7c946.png)

So, my questions are:
1) What exactly is this ip-addr? Looks like a local one, but is it node's or host's IP? I am currently launching both the node and the host on the same machine, so I have no way to check this.
2) Is there any way to NOT create an intermediate folder beetween `dest_path_prefix` and `dest_path`?
3) If 2) is NO, Is there any way to reliably get this ip-addr on the node (in `compute` function)? 

Why am I trying to achieve this:
I would like the directory structure to look like this:
<pre>
NodeDirectory/
    computation_executable (is launched from compute via os.system)
    computation_dependencies.dll
    ...
    dispynode.py
    dest_path_prefix/
         dest_path/
           &#60;here data files for computations will arrive&#62;
</pre>
And I would like the path `NodeDirectory/dest_path_prefix/dest_path` to always be predetermined so that my computation_executable would know where to look for files needed for computation.

Thank you in advance for your reply.

**Comment by pgiri** [comment]
dispynode adds IP address of client to `dest_path_prefix` so one client's computation doesn't affect another client's computation (e.g., a different user using same `comp_test` as destination). The IP address is address of client.

The computations usually shouldn't be affected by the path (folder) where files are saved on a node. Since computation's working directory is set by dispynode to be where files are saved, it is convenient (and portable) if computations use relative path (e.g., 'data_file1', or 'dir2/data_file21') instead of full path (`g:/host_distr_vjengine/.../comp_test/ip_addr/data_file1`). However, if for some other reasons you need a different directory structure (e.g., not refer to IP address), it may be possible to create symbolic link from computation's destination's path as created by dispynode to what you would like.

**Comment by max810** [comment]
Thanks, I got it. 
If `.` referse to the directory created by computation (where all the files will be received), and `dispy_job_path` variable indicates path to this directory - is there any way to simpy and reliably get the e.g. "root" directory path inside the `compute` function - I mean, the directory where `dispynode.py` is stored on the node and from which it is launched?

**Comment by max810** [comment]
Because something like `"../../../"` looks fragile and ugly, and just looking at all the parent directories is not reliable.

**Comment by pgiri** [comment]
I don't think I understand your question. In job computation, `os.getcwd()` will give directory where files would've been stored under. You can use standard Python functions to parse it as you need.

**Comment by max810** [comment]
Ok, I guess it's more of just Python task, than DisPy itself.
Thank you for your time.

**Comment by pgiri** [comment]
To reiterate, it is usually not necessary to know (root) directory where computation stores files, as dispy sets current working directory so computation can simply use relative paths. For example, to process `data_file2` (that would've been sent with `depends`), computation can use `fd = open("data_file2")` without reference to directory. This would make it portable so computation will work on another node (where dispynode may use different directory to store files).
