### ISSUE TITLE
Launch one job on one node with many CPUs/cores

### ISSUE THREAD

**Issue by max810** [pgiri/dispy#172]
Is there a way to launch ONLY ONE job simultaneously per node while using all the CPUs/cores on the node?

So, when on the node the first job is launched, it uses all the available CPUs/cores, it finishes, returns result and ONLY THEN the next job is started on that node.

**Comment by pgiri** [comment]
If your computation somehow can use all cores on a node, then you can by either starting dispynode with `-n 1` (so all computations only use one processor on a node) or by giving parameter `nodes` to `JobCluster` with instances of `NodeAllocate` where `cpus` is given as 1, or instances of subclass of `NodeAllocate` overriding `allocate` method that returns 1, etc.

**Comment by max810** [comment]
Thanks, with `cpus=1` eveything seems to work as intended.
