### ISSUE TITLE
EnvironmentError not caught

### ISSUE THREAD

**Issue by Dementiy** [pgiri/dispy#178]
When a new job was sent to unavailable dispynode (dispyscheduler doesn't know that it's unavailable yet because `ping_interval` is set to 60 sec), then we must fail on `run_job` with `EnviromentError` (`OSError` on Python 3.3+) because we can't establish a connection to the dispynode:

https://github.com/pgiri/dispy/blob/f74cdd20951a2ba2c05ead69813d0fa642db1d8d/py3/dispy/dispyscheduler.py#L1749-L1758

But based on source code we never catch this exception, because generic `Exception` raised in any case:

https://github.com/pgiri/dispy/blob/f74cdd20951a2ba2c05ead69813d0fa642db1d8d/py3/dispy/__init__.py#L764-L768

Also, I noticed two cases:
1. If we caught `Exception` then job has status `Running` and never scheduled on another node:

https://github.com/pgiri/dispy/blob/f74cdd20951a2ba2c05ead69813d0fa642db1d8d/py3/dispy/dispyscheduler.py#L1777-L1789

2. If we caught `EnvironmentError` then job scheduled on another node. When I restart the old node, it's rediscovered by scheduler, but doesn't accept new jobs.

https://github.com/pgiri/dispy/blob/f74cdd20951a2ba2c05ead69813d0fa642db1d8d/py3/dispy/dispyscheduler.py#L1758-L1776

**Comment by pgiri** [comment]
The fix committed above may address this (partially). I haven't tested it (yet), but I think it should cause scheduler's ``run`` method to get ``OSError`` and ``EnvironmentError`` as expected. I remember quite a few releases ago, ``_DispyJob_.run`` sent the request directly instead of passing to ``_Node.send``, so exceptions would be thrown to the caller. The simplification broke that.

The above fix may not be sufficient to handle all the symptoms you experience, but if you get a chance to test and see what works / what doesn't, it would be great.

Thanks.

**Comment by Dementiy** [comment]
Thanks.

`EnviromentError` is caught as expected. But when I restart dispynode it doesn't accept any new jobs from cluster. Maybe because we discard cluster from node:

https://github.com/pgiri/dispy/blob/266ccd5ca5867317d0668f11200130c78545234b/py3/dispy/dispyscheduler.py#L1758-L1761

And when node rediscovered this condition is true:

https://github.com/pgiri/dispy/blob/266ccd5ca5867317d0668f11200130c78545234b/py3/dispy/dispyscheduler.py#L1377-L1379

So `cluster` will not be added to the `node.clusters`:

https://github.com/pgiri/dispy/blob/266ccd5ca5867317d0668f11200130c78545234b/py3/dispy/dispyscheduler.py#L1395-L1398

**Comment by pgiri** [comment]
I am not entirely sure that the above fix is appropriate / has any side effects. Let me know if you have any comments.

**Comment by Dementiy** [comment]
Thanks.

I think it also makes sense to remove node address from `cluster._dispy_nodes` inside `run_job` function:

```python
cluster._dispy_nodes.pop(node.ip_addr, None)
```

Otherwise this node will be unavailable for existing computaions, because `node.clusters` is empty set and `cluster._dispy_node` contains the node address:

https://github.com/pgiri/dispy/blob/fa9ce4d67e122f8a8646898c4d24e49c86436cc8/py3/dispy/dispyscheduler.py#L1377-L1379

**Comment by pgiri** [comment]
Thanks for catching the mistake of not removing from `_dispy_nodes`. It is fixed now. Unless something else comes up, I am thinking of releasing 4.10.6 this weekend / early next week.

**Comment by Dementiy** [comment]
Thanks a lot, everything works as expected!

Waiting for 4.0.6.
