### ISSUE TITLE
Passing classes to setup/cleanup/compute still does not work

### ISSUE THREAD

**Issue by matthewwardrop** [pgiri/dispy#18]
Hi pgiri,

Your implementation fails to properly make the classes available to the setup/compute/cleanup functions. This is because unlike in my code, where I specified only a global dictionary, you specify both global and local dictionaries; which does not behave as you might expect.

Try running:

```
code = '''
def test():
    print globals().keys()
    print locals().keys()
'''

global_keys = {'global_key':1}
local_keys = {'local_key':2}

exec(code, global_keys, local_keys)
exec("test()", global_keys, local_keys)
```

Notice that locals() only includes variables in the local function scope; and globals does not include the values from locals, as you might think.

Can I suggest modifying the implementation to be closer to how I had it? Or is there some other clever way to fix it?

M

**Comment by matthewwardrop** [comment]
Hello again,

With the current master code, I still cannot send classes to be used by setup. Provided is a demonstration of that:

```
class Greeter(object):

    def __init__(self, greeting='Hello'):
        self.greeting = greeting

    def greet(self, name="Matthew"):
        print "%s %s" % ( self.greeting, name)

def compute(name):
    greeter.greet(name)

def callback(job):
    print job.stdout

def setup_simple():
    global greeter
    salutation = "HI"
    greeter = Greeter(salutation)
    return 0

from dispy import JobCluster

class BigComplexClass(object):
    greeting = "Hiya"
    names = ['Matthew', 'Mark', 'Luke', 'John']*100

    def run_jobserver(self):

        g = Greeter(greeting='best')

        cluster = JobCluster(compute,
            setup=setup_simple, # This will work
            depends=[Greeter],
            callback=callback)

        for name in self.names:
            cluster.submit(name)

        cluster.wait()
        cluster.stats()
        cluster.close()

if __name__ == "__main__":
    bcc = BigComplexClass()
    bcc.run_jobserver()
```

I also notice that you reverted the private context patch, since it would break several things. I think my original patch maintains gives the benefits of encapsulation without breaking anything; and indeed _fixing_ this current problem. Are you interested in my reworking that for the current code in `master`? Quite happy to do it.

**Comment by pgiri** [comment]
Instead of creating objects in client and sending them to 'setup', create them in 'setup'. 'setup' is not meant for computation; it is to prepare the node for subsequent computation jobs.

I don't think sending 'context' or strings to inject into node are good ideas, as I mentioned before. One of the features/goals of dispy is to require very little change in the code to use it - if you have a Python program that runs as a sequential program, it should require just creating a cluster, and scheduling jobs. 'setup' and 'cleanup' are necessary in some cases to prepare depenedencies transferred. 'context' that you propose is not an inherent concept and while it may serve your purpose, makes it even harder for others to understand / use / debug programs.

Maintaining context in a variable instead of using 'globals' when 'exec'ing has issues. While this implementation can be fixed up so it works with provisional result and sending files, I am not sure it is safe (works for all cases), or efficient (especially if there is lots of data initialized in 'setup').

If you have a solution that works for you, please post it; others may find it useful / interesting.

**Comment by matthewwardrop** [comment]
Hi pgiri,

Thanks for your response. I actually wasn't advocating using `context` as I originally proposed. I understand your point of you regarding the addition of new concepts that just make things more complex. [I still feel, though, that providing a way to send objects from the local namespace to the global namespace of the computation on the cluster is useful; and not necessarily a new concept. Labelling it "globals", instead of "context", I think solves most of the confusion... but I digress!].

The issue addressed here is that classes are not actually being exposed in the namespace of the `setup` function. If you run the code I've provided above, I think you'll find (as I did) that the class `Greeter` is not available inside of `setup`. This is a bug according to the stated behaviour of `JobCluster` and the keyword `depends`. The original patch I provided did not expose the `context` dictionary to the world, and encapsulation wasn't actually the goal... the goal was to fix this bug.

Are you not able to reproduce it?

M

**Comment by pgiri** [comment]
Hmm, 'setup' is not computation! The things available to 'setup' are the files copied so it can prepare / read them, initialize global variables, for example.

**Comment by matthewwardrop** [comment]
Okay... I'm confused. The documentation says the classes can be sent via `depends`; and the source code ratifies that. The classes are appended to `compute.code`. When this code is "marshalled", the classes are then compiled on the cluster; but are unavailable to setup (and compute/etc) due to namespace issues.

Am I missing something?

**Comment by matthewwardrop** [comment]
Also, shouldn't it be possible to do "once-off" general computation in `setup`, if doing it there means you don't need to do it in every call to `compute`? Especially if that required initialisation is slow.

**Comment by matthewwardrop** [comment]
I do not want to push you into including things in your project which you consider suboptimal, but I am about to publish some software which I would like to interface with dispy for distributed parallelisation. If you could clarify the issues raised in my two former messages, I'd be very grateful. It might just be that I need to maintain a fork in order to get it to do what I need :). Obviously, though, it would be nicer if I didn't have to maintain a separate project.

**Comment by pgiri** [comment]
I believe most of the issue(s) are addressed in latest release. If this is not the case, please create new issue.
