### ISSUE TITLE
Wrong broadcast address

### ISSUE THREAD

**Issue by jackluo923** [pgiri/dispy#187]
In ```dispy/__init__.py:397-399``` in the python3 pip package, bug may overwrite correct broadcast messages on both Linux and Windows. The corresponding lines are ```py3/dispy/__init__.py:415-417``` on 83e11a5a90d679f2828d9dbd330755c42aa258a0 commit.

```
397 # Windows seems to have broadcast same as addr
398 if broadcast.startswith(addr):
399    broadcast = '<broadcast>'
```
1. I'd suggest that to restrict this check to be a Windows only check. Currently this check also executes on Linux based system. 
2. Line 398 does not do what the comment says and leads to incorrect behavior
- For example an IP ```142.1.136.6``` has broadcast IP of ```142.1.136.63```
- Current code will overwrite the correct broadcast IP to ```<broadcast>``` which is the wrong behavior

Pull request link: https://github.com/pgiri/dispy/pull/189

**Comment by pgiri** [comment]
Thanks for the patch. I don't know if extra ``os.name == 'nt'`` is required, but for now it is probably safe that way (until it is known other platforms also work that way).
