### ISSUE TITLE
Confusing README and possibly incorrect implementation

### ISSUE THREAD

**Issue by jackluo923** [pgiri/dispy#188]
The dispynode.py port section of the  [readme](http://dispy.sourceforge.net/dispynode.html) is incredibly confusing. 

In the distscheduler documentation, ```--port=n``` specifies communication for job results while ```--scheduler_port=n``` specifies the port for job scheduler. 
In distpynode.py documentation ```--scheduler_port=n``` corresponds to ```--node=n``` in the scheduler (communication job results). However, due to the naming similarity, it's very confusing.

**Comment by pgiri** [comment]
In case you have noticed, port setup is completely revamped in current master. New version will be released this weekend / early next week, so please check new version (and new documentation) when it is released.

**Comment by jackluo923** [comment]
@pgiri I am not aware of the revamped version because I've only started using dispy yesterday. I'd love to check out the new version. 
Thanks for the suggestion and fast response.
