### ISSUE TITLE
Invalid node when using submit_node

### ISSUE THREAD

**Issue by demiangomez** [pgiri/dispy#190]
I'm getting a similar error as reported on issue #97, but not only on the localhost. When I try to send a job to a specific node, no matter how much time I wait, I get an "Invalid node" message. I need to use `submit_node` because I test all the nodes one by one to make sure that all dependencies and programs are available before running a task.

My code is very simple:

            self.cluster = dispy.JobCluster(tt, servers, recover_file='pg.dat', pulse_interval=60,
                                                cluster_status=self.check_cluster, ip_addr=self.ip_address,
                                                loglevel=dispy.logger.DEBUG)
            self.cluster.discover_nodes(servers)

            # wait for all nodes
            time.sleep(DELAY)  # DELAY = 5 right now

            for node in self.nodes:
                j = self.cluster.submit_node(node, self.check_gamit_tables, self.software_sync)
                self.cluster.wait()
                self.result.append(j.result)

self.nodes is populated in self.check_cluster:

    def check_cluster(self, status, node, job):

        if status == dispy.DispyNode.Initialized:
            print ' -- Checking node %s (%i CPUs)...' % (node.name, node.avail_cpus)
            # test node to make sure everything works
            self.cluster.send_file('gnss_data.cfg', node)

To avoid any problems with the code that checks the node, I've implemented a dummy function like this:

    def tt(check_gamit_tables=None, software_sync=()):

        print 'hello world!'
        return ' -- error'

If I call `submit()`, everything works fine, but I can't check the individual nodes. I'm using dispy version 4.10.6 on a Mac with Sierra.

Any ideas what might be the problem?

Thanks,

**Comment by pgiri** [comment]
Can you try 4.11.0 version? There was an issue with `submit_node` in 4.10.6.

**Comment by demiangomez** [comment]
Updated to 4.11.0 and the problem is gone! Thanks! I'm closing the issue.
