### ISSUE TITLE
Sequential Job Execution

### ISSUE THREAD

**Issue by Abhay7417** [pgiri/dispy#192]
I am using JobCluster to send jobs (which contain TensorFlow code execution) to server. Currently, multiple jobs assigned to a single node starts executing simultaneously which leads to memory issue as well as GPU memory issue. How to run jobs in a sequential fashion on each node, such that if one job is getting executed another job should be in the queue.
Thanks in advance for the help.

**Comment by pgiri** [comment]
You can specify nodes as having 1 CPU, e.g., with `cluster = dispy.JobCluster(compute, nodes=[dispy.NodeAllocate('*', cpus=1)])`.

**Comment by Abhay7417** [comment]
Thanks, It resolved the issue.
