### ISSUE TITLE
Ignoring node $correct_node_ip due to "secret" mismatch

### ISSUE THREAD

**Issue by odo2063** [pgiri/dispy#199]
Hi!

I get "Ignoring node $correct_node_ip due to "secret" mismatch"

at first I start the node in dockercontainer(network_mode: host)
with `/usr/local/bin/dispynode.py --clean`

then I start `dispyscheduler.py -n $correct_node_ip` on my machine

then this:
```
def calcByDegree(degrees, radii):
	import dispy as dis
	cluster = dis.JobCluster(calcByRadius, depends=[pol2cart, calcByRadius])
	raster = []
	
	for deg in degrees:
		coordByDegree = []
		coordByDegree = cluster.submit(deg, radii)
		raster.append( coordByDegree )
	return raster
```
will be executed my main machine.

from python I get : 

> dispy - Port 61590 seems to be used by another program ...

and from the scheduler I get: 

> dispyscheduler - Ignoring node $correct_node_ip due to "secret" mismatch

What do I miss here?

dispyscheduler version 4.11.0
dispynode version: 4.11.0

**Comment by odo2063** [comment]
same happens with following setup on my machine only:
```
dispynode.py --secret=geheim
dispyscheduler.py --node_secret geheim
cluster = dis.JobCluster(calcByRadius, depends=[pol2cart, calcByRadius], secret='geheim')
```

**Comment by pgiri** [comment]
With your setup, you need to specify `cluster_secret` with dispyscheduler, which, if you wish, can be different from `node_secret`. Or, you can drop `secret=` from `JobCluster` since you are not using cluster secret with dispyscheduler.

**Comment by odo2063** [comment]
Also happens when i remove all "secrets"

**Comment by pgiri** [comment]
With dispyscheduler, you need to use `dispy.SharedJobCluster`, instead of `dispy.JobCluster`.

If that doesn't work, try without dispyscheduler and make sure that Python version is same; it may be better to start with `python3 dispynode.py` and `python3 client_prog.py` etc.

**Comment by odo2063** [comment]
OK, so just `dispy.JobCluster` plus `dispynode.py` it is...

`dispy.SharedJobCluster`, gives `socket.gaierror: [Errno -2] Name or service not known`....

Now i need to find out how to get my list[] instead of <dispy.DispyJob object at 0x7f0da4ca5228>...any hinds?

**Comment by pgiri** [comment]
`cluster.submit` returns `DispyJob` instances. You can use them as functions to get the results, e.g., with `job()`, or once job is finished, with `job.result`. See `sample.py` and other examples in the package or in documentation.

**Comment by odo2063** [comment]
just asking...could you provide `easy_sample.py` with just send computation(e.g.` x= i +i`), store result on client `x= some.result` and `print (x)`?

**Comment by odo2063** [comment]
ok...the `example.py` here is much more useful for noobs like me. I think i got it working. One last Question. If i use the "path attribute", can I put my modules, additional files in that directory on the client and it will just `import` the stuff?

**Comment by odo2063** [comment]
close while no further awnser...
