### ISSUE TITLE
How to share CFFI module to cluster?

### ISSUE THREAD

**Issue by odo2063** [pgiri/dispy#204]
Hi!

How may I cluster.submit a function that calls a cffi module/library?

```
from lib._eff import ffi, lib
import dispy as dis
	
cluster = dis.JobCluster(checkEffectivity2, 
					 depends=[lib, ffi]
							)
```
gives 
`AttributeError: cffi library '_eff' has no function, constant or global variable named '__file__'`

**Comment by pgiri** [comment]
dispy needs to get Python source for functions to be distributed. In this case, library is likely binary so not possible to obtain source lines. Instead, send the library and import necessary functions in computation from the library. It is even possible nodes already have the library, in which you don't need to distribute it - only components not available on nodes need to be distributed.

**Comment by odo2063** [comment]
It is selfwritten cffi-code.

```
cluster = dis.JobCluster(checkEffectivity, 
							 depends=[  'lib/_eff.c', 
							 			'lib/_eff.o', 
							 			'lib/_eff.cpython-36m-x86_64-linux-gnu.so']
							)
```

seems to work fine...Thanks for great work!
