### ISSUE TITLE
Sklearn package with n_jobs

### ISSUE THREAD

**Issue by oomjos** [pgiri/dispy#211]
Hi,

Is there a way to distribute the calling an Sklearn module, that has its own parallelism parameter (n_jobs), over my network cluster?

Any advice or guidance would be sincerely appreciated.

Thank you.

**Comment by pgiri** [comment]
Client can specify that dispy should use only 1 cpu per node; e.g., with "NodeAllocate" (see "node_setup.py"). Alternately, dispynode can be started with cpus parameter, e.g., "dispynode.py --cpus 1" (with this all clients can only use 1 cpu whereas with first use case other clients can use all cpus).

**Comment by oomjos** [comment]
Thank you for the response.

I think I have a better idea now on how to approach it.

Basically when decalring a Sklearn module with njobs=-1 (use all the available CPU's) I want the Sklearn module to not only use the local PC's cores but also all of the available dispy server nodes cores.

Thank you.

**Comment by pgiri** [comment]
My suggestions above work as you wanted: Sklearn can use all processors on a node and dispy distributes and schedules to nodes in cluster.

**Comment by oomjos** [comment]
Thank you.
