### ISSUE TITLE
unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by elogy** [pgiri/dispy#213]
Hey everybody,
I'm starting new with dispy and currently running into a problem. I'm not sure if this is the right place to ask, feel free to point me to another place which might be better suited for the question. 

Both client and server are running dispy version 4.12.2. However, the dispy client is running under Python 3.8, whereas my two dispy servers are both running Python 3.7. This seems to cause problems when trying to communicate, since Python 3.8 defaults to Pickle version 5, which is not yet available in 3.7. 

I set up the cluster as follows:
```python
 dispy_cluster = dispy.JobCluster(ffmpeg_job,
                                     nodes=DISPYNODES,
                                     recover_file=DISPYRECOVERY,
                                     secret=DISPYSECRET,
                                     ip_addr=DISPYSERVER)
```
Where DISPYNODES is a list of IP addresses: `DISPYNODES = ["192.168.134.235", "192.168.134.230"]`

I then try to run the method that is initializing the JobCluster. 

The output on the server:
```
2020-08-12 11:27:53 dispynode - dispynode version: 4.12.2, PID: 5006
2020-08-12 11:27:53 dispynode - Files will be saved under "/tmp/dispy/node"
2020-08-12 11:27:53 pycos - version 4.8.15 with epoll I/O notifier
2020-08-12 11:27:53 dispynode - "timmsodroid" serving 6 cpus
2020-08-12 11:27:53 dispynode - TCP server at 192.168.134.235:61591

Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "release" to check and close computation,
  "cpus" to change CPUs used, anything else to get status: 2020-08-12 11:28:01 dispynode - Traceback (most recent call last):
  File "/usr/local/bin/dispynode.py", line 1804, in tcp_req
    info = deserialize(msg[len(b'PING:'):])
  File "/usr/local/lib/python3.7/dist-packages/pycos/__init__.py", line 79, in deserialize
    return pickle.loads(pkl)
ValueError: unsupported pickle protocol: 5
```

I then tried to use another pickle procotol version by (quite hackily) overwriting the dispy.serialize function using pickle5:

```python
def serialize(obj):
    pb = pickle5.PickleBuffer(obj)
    pickle5.dumps(pb, protocol=3)

dispy.serialize = serialize
```
This, as you can probably guess, didn't work. :D All that is then transferred is an initial string of "xxxxxxxxxx" characters, resulting in a "Ignoring invalid request from […]" message, but no ping message or anything else. (Sniffed the ethernet traffic with Wireshark)

Is there a way I can get different python versions to communicate with each other without faffing around with venvs or manually upgrading the Python version on the servers?

**Comment by pgiri** [comment]
If you replace `serialize` in pycos, it should work. In client program, before importing dispy, define:

    import pycos, pickle
    def serialize(obj):
        return pickle.dumps(obj, protocol=4)

    pycos.serialize = serialize

I will make the protocol version configurable in the next version.

**Comment by elogy** [comment]
Yup, this works like a charm.
Thanks! :+1:
