### ISSUE TITLE
Sample code for using NodeAllocate?

### ISSUE THREAD

**Issue by rarmstrong22** [pgiri/dispy#23]
Hello,

This is really a documentation request, not a bug: could we see an example of passing NodeAllocate objects to ShareJobCluster()? I've been attempting to do so, with no luck (seems like my NodeAllocate objects are ignored):

    nodes = []
    nodes.append(NodeAllocate('10.8.16.16', port=None, cpus=48))
    nodes.append(NodeAllocate('10.8.16.18', port=None, cpus=12))
    cluster = dispy.SharedJobCluster(my_compute_function,
                               nodes=nodes,
                               callback=job_complete_cb,
                               ip_addr=my_config['cluster_host_ip'],
                               scheduler_node=my_config['cluster_scheduler_ip'])

Is this the correct approach? Any advice is greatly appreciated.
Rick

**Comment by pgiri** [comment]
When SharedJobCluster is used CPUs are ignored (because another program / cluster could also use the scheduler that would be prevented if one program reduces number of CPUs). However, the IP addresses should be honored; i.e., your cluster would use given nodes and another cluster could use other nodes found. So your setup as given above should work, except for CPUs. If that is not the case, please give more details on what is not working.

**Comment by rarmstrong22** [comment]
> So your setup as given above should work, except for CPUs. 
> If that is not the case, please give more details on what is not working.

Ok, it appears to be working as designed, then. Thanks very much for your response. Excellent tool, and thanks for putting the source out there!

**Comment by pgiri** [comment]
BTW, if you have access to dispyscheduler (e.g., you start it yourself), then you can start it with '--httpd' and then manage the cluster with a web browser (from dispyscheduler's http interface), including changing the CPUs dynamically. This may not be convenient for you, but in case that suffices, you can use it that way.

**Comment by pgiri** [comment]
Sorry to post another reply to closed ticket (I hope you see / are notified of updates to closed tickets).

With version 4.6.0 (released today), you can control scheduling in client. See 'job_scheduler.py' in the 'examples' directory on how to use this feature. Briefly, in cluster_status callback you can keep track of how many jobs are scheduled on which node and schedule jobs appropriately.

**Comment by rarmstrong22** [comment]
Thanks for the heads-up, I'll take a look at the latest.

**Comment by pgiri** [comment]
In case you are interested in this feature (setting CPUs with SharedJobCluster): With 4.6.10 version, you can start dispyscheduler with 'cooperative' which allows clients to update CPUs of nodes. Or, 'exclusive' clients can also change CPUs.
