### ISSUE TITLE
Example for distributing a function with multiple functional dependancy

### ISSUE THREAD

**Issue by Ebinu** [pgiri/dispy#24]
Sir,
 Could you please give some examples on how to diatribute a function whose valus depends on another functions or variable. I am working on my main project with clustering in python.

**Comment by pgiri** [comment]
I don't think I understand the question, but here is an attempt at what I think it is.

Assume that your computation is a function "f" which uses another function "g":

    def f():
        return g()
    def g():
        ...

Then you can send "g" in "depends" with:

    cluster = dispy.JobCluster(f, depends=[g])

You can't send variables with this approach, as not all variables (e.g., class objects) may not be serializable. Instead, you can create them on nodes with a "setup" function.

**Comment by Ebinu** [comment]
Sir,
Suppose I have a code of form
def f1():
return f1

def f2():
   f1()
return f2

def f3()
  f2()

how can I distribute f3 using dispy and if I have list values as arguments
which is the output from another function how will I distribute as such

**Comment by pgiri** [comment]
I am not sure what exactly is the problem you describe, but here is my guess. First, send all three functions with:

    cluster = dispy.JobCluster(f3, depends=[f1, f2])

So when function f3 is executed, it will return result of executing f2 (which in turn returns what f1 returns). I am not sure why the functions return themselves, though.

As for submitting list as arguments, I assume you mean to pass each element as separate argument to f3? (Then why doesn't f3 have an argument?) I am going to assume a function f is computation that has one formal argument. In which case, you can execute it with each element in a list as:

    def f(arg): return arg
    cluster = dispy.JobCluster(f)
    jobs = []
    for i in range(10):
        jobs.append(cluster.submit(i))
    for job in jobs:
        print('result: %s'  % job())

I also don't understand why you filed this an issue with dispy.

**Comment by Ebinu** [comment]
Sir,

Suppos I have to distribute and parallelize a function f which deals with
rndomly splitted data being distributed suppose i have a

def f():
 with open('filename') as f:
  do some computation
return f
Suppose i have anode1 and node2 this function f has to do the computation
on node1 with the file on node1 as well as i have to distribute function f
to node2 and do the computation with the  file on node2 at the same time
parallelization. I am finding difficulty in parallelizing  the function
with the the computation ath the same time with two different files at same
time is it possible with dispy?
I know to distribute in a client server manner but to do parallelzation
with two different file for the same function at same time what can I do

**Comment by pgiri** [comment]
You can send job specific files with *dispy_job_depends* parameter; see http://dispy.sourceforge.net/dispy.html#cluster for details. If you don't care which file is processed on which node, client can use

  cluster.submit(f, dispy_job_depends=["file1"])
  cluster.submit(f, dispy_job_depends=["file2"])

etc. If you want node1 to process "file1", then you can use *submit_node* (see *job_scheduler.py* example).

**Comment by pgiri** [comment]
This is not an issue in dispy.

**Comment by Ebinu** [comment]
Sir,
suppose i want to distribute a function that depends on other function for
more than once is it enough that I give within depends the function name
only once. I have been stuck with this only line for nearly two days sir.
Please do help me sir,
def locality( Medoid , mrval):
     with open(urlPath) as f:
    reader = csv.DictReader(f)
    for row in reader:
     temp=list(row[x] for x in full_data)
     datalist.append(temp)
     cat_temp=list(row[x] for x in cat_name)
     unique_set.append(cat_temp)
    num_colums=len(datalist[0])
    f.seek(0)
    row_count=sum(1 for row in f)
    indices.append(num_colums)
    indices.append(row_count)
    b=indices[0]
    c=indices[1]
    attr=[2,2,1,1,1,1,2,1,1,1,2,1,2,2,2,2,1]
    attribute_types=[int(x) for x in attr]
    data=[]
    l=findIndex(1,attribute_types)
    integerIndices=findIndex(2,attribute_types)
    for x in range(len(cat_name)):
              for i in unique_set:
                colum_list.append(i[x])
    chunk=row_count-1
    result = [colum_list[i:i+chunk] for i in range(0,len(colum_list),chunk)]
    for i in result:
        r.append(set(i))
    li=list(zip(r,l))
    for i in range(len(cat_name)):
             myList[cat_name[i]]=li[i]
    for i in datalist:
            for j in integerIndices:
                i[j]=int(i[j])
    for i in datalist:
            for k in i:
                data.append(k)
    Data = []
    Data = [data[i:i+b] for i in range(0, len(data), b)]
    binaryIndices = findBinaryIndices(myList,binaryList)
    categorical = findCategorical(cat_name,binaryList)
    for i in categorical:
            categoricalIndices.append(myList[i][1])
    resultRandom = ranNumGenerator(K)
    rep=list(chain.from_iterable(datalist[i] for i in resultRandom))
    slicedList= [rep[i:i+b] for i in range(0, len(rep), b)]
    myList2={}
    for val in categoricalIndices:
         myList2[full_data[val]]= findUniqueValues(slicedList,val),val
    ind=0
    myVals = []
    countDict1 = []
    for k in categorical: # k gives the name of the attribute
        ind = myList2[k][1]
        #print("ind",ind)
        for vals in myList2.get(k):
                  if(type(vals)==set):
                   del myVals[:]
                   myVals.append(vals)
                   #print("myvals",myVals)
                   for j in myVals:
                       for ll in j:
                           countDict1.append(findCount(slicedList,ind,ll,k))
    dict1=[]
    dict2=[]
    p = []
    dum = []
    p2=defaultdict(list)
    for k in categorical:
        for m in categorical:
         del dict1[:]
         dict1.append(myList2[k][0])
         indexX = myList2[k][1]
         if(k==m):
           continue
         if myList2[m] not in dict1:
           del dict2[:]
           dict2.append(myList2[m][0])
           indexY = myList2[m][1]
           for x in dict1:
               for lz in x:
                   attrX = lz
                   for m in dict2:
                       for n in m:
                            attrY = n
                            for x in countDict1:
                                del dum[:]
                                if((x[0]==k) and (x[1] == attrX)):
                                   countX = x[2]

                            dum.append(attrY)
                            dum.append(indexY)
                            dum.append(attrX)
                            dum.append(indexX)
                            p2[str(dum)]

p2[str(dum)].append(findProbability(slicedList,indexX,attrX,indexY,attrY,countX))


    index = 0
    count = 0
    nearstmid = [0]*len(mrval)
    premed = [0]*len(mrval)
    med = [0]*len(mrval)
    dmed = [0]*len(rval)
    locality = defaultdict(list)
    mnj = len(rval)-1
    print("mmmmmnn0",mnj)
    j = len(mrval)-1
    print("jjj",j)

    while(count <= j):
        temp = mrval[index]
        for i in range(0,j+1): #submedoid table
            temp1 = mrval[i]
            if(count == 0 and i == 0):
                nearstmid.append(temp[0])
                premed[i] =9999999
            if(temp1[0] != temp[0]):
                med[i] = distance(p2,mrval[index] ,
mrval[i],integerIndices,l,binaryIndices,categorical)[2]
                if(count == 0 and i != 0):
                    nearstmid[i] = temp[0]
                    premed[i] = med[i]
                else:
                    if(premed[i] > med[i]):
                        premed[i] = med[i]
                        nearstmid[i] = temp[0]

         #end for loop
        count += 1
        index += 1
    #end of while loop

    index = 0
    temp2 = []
    while(index <= j):
        i = 0
        temp = mrval[index]
        for i in range(0,mnj+1):
            temp2=rval[i]
            dmed[i] = distance(probabilityList2,mrval[index] ,
Datal[i],integerIndices,l,binaryIndices,categorical)[2]
######################I am stuck here whenever I run this line it is shown
None type object is not iterable
Sir I am planning to do a submission by march 30 nd unfortunately my time
is being gone just spending time on this last portion of the code. Please
please please do help me
.............................
........................
if __name__ == '__main__':
    import dispy, random
    import csv
    from collections import defaultdict
    cluster =
dispy.JobCluster(locality,depends=[findIndex,findBinaryIndices,findCategorical,ranNumGenerator,findUniqueValues,findCount,findProbability,distance])
    jobs = []
    for i in range(2):
        # schedule execution of 'compute' on a node (running 'dispynode')
        # with a parameter (random number in this case)
        job = cluster.submit()
        job = cluster.submit()
        job.id = i # optionally associate an ID to job (if needed later)
        jobs.append(job)
for job in jobs:
        host,slicedList,countDict1,j2=job()
        print('%s executed job %s at %s' % (host, job.id, job.start_time))
        print(host)
        print(slicedList)
        print(countDict1)
        print(j2)
    cluster.stats()
    cluster.close()
