### ISSUE TITLE
Impossible to send dependencies to a "Program" job

### ISSUE THREAD

**Issue by Sigill** [pgiri/dispy#29]
Both the `cluster.submit()` and `cluster.submit_node()` methods contains this piece of code:

```
if self._compute.type == _Compute.prog_type:
  if kwargs:
    logger.warning('Programs can not have keyword arguments')
    return None
```

which prevents the use of dependencies at job level when the job is a Program.

This test seems to be too restrictive. Keyword arguments should indeed be forbidden for Programs, but the `dispy_job_depends` argument does not seems to have anything to do with the job's type. Keyword arguments should therefore be allowed as long as it only contains the `dispy_job_depends` argument.

**Comment by pgiri** [comment]
Fix committed. Confirm and close if it works.

**Comment by Sigill** [comment]
Commit e24698db2551f80b6dbebc5e41096e7c01602a09 closes this issue.
Thanks a lot @pgiri.
