### ISSUE TITLE
Where is the latest code?

### ISSUE THREAD

**Issue by matthewwardrop** [pgiri/dispy#3]
Greetings!
I notice that when I do a pip install I'm downloading dispy 4.0; but the svn repo on sourceforge is old, as is the code here. I found a bug in the code, and am wondering where I should post it.

**Comment by pgiri** [comment]
Hi,
Sorry right now the repository is not up-to-date. I have been meaning to merge svn, git but haven't had the time. I will do that once next version 4.1 is released.
Please send the patch against 4.0; unless it is extensive, it shouldn't be difficult to merge against my current development brach. Thanks for patch in advance!
Cheers, Giri 


     On Thursday, April 30, 2015 3:49 AM, Matthew Wardrop <notifications@github.com> wrote:
   

 Greetings!
I notice that when I do a pip install I'm downloading dispy 4.0; but the svn repo on sourceforge is old, as is the code here. I found a bug in the code, and am wondering where I should post it. —

**Comment by matthewwardrop** [comment]
It is very not-extensive :).

--- "__init__ (copy).py"	2015-05-01 15:16:37.787434000 +1000
+++ __init__.py	2015-05-01 15:16:56.144384144 +1000
@@ -1058,6 +1058,7 @@
                 node.clusters.discard(compute.id)
                 logger.warning('Failed to setup %s for compute "%s"', node.ip_addr, compute)
                 yield node.close(compute, coro=coro)
+                cluster = self._clusters[compute.id]
                 if cluster.status:
                     self.worker_Q.put((cluster.status, (DispyNode.Closed, node.dispy_node, None)))
             else:

I did find 4.0 to be a unreliable compared to 3.23 (in very limited testing), though. You can see my implementation in https://github.com/matthewwardrop/python-parampy/blob/master/parampy/utility/symmetric.py (as DistributedParallelMap). I will test 4.0/4.1 again in the future, but for now, 3.23 is serving me well. Thanks again for this fantastic software :).

**Comment by matthewwardrop** [comment]
Glad to see that 4.2 is now in the repository. Thanks!
