### ISSUE TITLE
logging causes does not work on nodes

### ISSUE THREAD

**Issue by grantstephens** [pgiri/dispy#33]
Good afternoon

I am trying to use my logger that is set up for the module when the multiprocessing starts running so that each node's log entries will wither get printed to stdout or ideally to the log file. I've tried multiple ways, but I cannot get any log entries to show up, even if just in the stdout. When calling `logger.debug('test')` for example I get the following error:
`logging.FileHandler.emit(self, record)
AttributeError: 'NoneType' object has no attribute 'FileHandler'`
This happens when trying to log to a file or if the hander is simple s streamhandler that should log to stdout. I've also tried redeclaring the logger in the class but to no avail.

**Comment by pgiri** [comment]
I am not sure I understand the problem. Are you trying to do this in dispynode to show logs? If you use '-d' option (i.e., 'dispynode.py -d'), it should print. If you are putting logging statements in client computation, then that may not / won't work - dispynode captures all output, error and exception and sends back to job, available as job.stdout, job.stderr and job.exception. If you want to create your own log information on jobs at the client, you can supply 'cluster_status' or 'status' callbacks when creating cluster.

**Comment by RexFuzzle** [comment]
Ok, so it on the client side. and I normally simply log with `logger.debug('Test')` but this does not come back to job.stdout or stderr or exception. Usually the logger is setup to write all the logger.debug/warning/ to a output.log  and I understand that this would be very difficult to get working as multiple processes have to access the same file, however when the logger is set to print to stdout, (config something like `console_handler = logging.StreamHandler()` and `logger.addHandler(console_handler)`) then these outputs do no show up in job.stdout.

**Comment by pgiri** [comment]
Use print statements in the client computation; they should be in job.stdout.

**Comment by RexFuzzle** [comment]
Unfortunately its a 3rd party library with a lot of logging statements and so I'd have to go in and edit all the logging statements

**Comment by pgiri** [comment]
I am guessing that you are simply using 'logger' variable in your jobs, without creating it in job. This logger is for dispynode, not for jobs. In fact, if you enabled dispynode with debug, these messages could be seen in dispynode's output (not job's stdout). In the next version 'logger' is removed, so jobs can't use it. If you want to use logger, you should create one in each job appropriately. You also can't create it in 'setup', as that is run in dispynode process (which is different from job's process). If the logger created in job prints to stdout, then this will show up in job.stdout (you may need to make sure to flush logging output before job finishes for it to show up in stdout).

**Comment by pgiri** [comment]
As mentioned above, using 'logger' in jobs is not supported (current release doesn't even have 'logger'). If you need to make logging available in 3rd party computations, create 'logger' in your job computation before calling functions in external library. That should work. Closing this issue; file new issue if necessary.
