### ISSUE TITLE
dispynode holding file pointer that grows until restarted

### ISSUE THREAD

**Issue by adam-douglass** [pgiri/dispy#35]
On long running instances of dispynode I've encountered node crashes from the disk filling up, with no files on disk actually taking the space. So I checked what file handles dispynode has open, assuming it is a deleted file that is being held open by the python process. There are lots of other files open for pipes, sockets, the python executable and libraries, but standing out from the rest are two handles to a unlinked temporary file that grows as the dispynode runs.

COMMAND    PID   USER   FD   TYPE             DEVICE   SIZE/OFF   NODE NAME
dispynode 1070 worker    1u   REG              202,1 5041904045   8408 /tmp/tmpf1aO2R4 (deleted)
dispynode 1070 worker    2u   REG              202,1 5041904206   8408 /tmp/tmpf1aO2R4 (deleted)

again a few minutes later:

dispynode 1070 worker    1u   REG              202,1 6115275750   8408 /tmp/tmpf1aO2R4 (deleted)
dispynode 1070 worker    2u   REG              202,1 6115275750   8408 /tmp/tmpf1aO2R4 (deleted)

I'm not sure exactly what temporary file is being held open. I'm going to try to find it, but any advice about what components might be keeping something open as long as the main dispynode process is open would help.

**Comment by pgiri** [comment]
Good find! I wasn't aware of this issue. Let me take a look and come back. 

Is it possible there are/were errors, for example, computations failed? The right way to use file descriptors is to use 'with' statement, so in case of errors, the descriptor is closed automatically.

**Comment by adam-douglass** [comment]
I have it going now after a clean reboot and no failures in the jobs submitted (the output from lsof above is from this run). The job isn't opening any files itself. But I am sending some files with the depends argument, and moving them into a subdirectory as a work around for a module that wasn't being sent over properly.

**Comment by pgiri** [comment]
Is it likely that you are using _setup_ to copy the dependencies as you mention? If you are copying files, are you closing files (as I pointed above, using _with_ will be easier)?

Can you describe the problem with dependencies not being copied properly (probably as separate issue)?

**Comment by adam-douglass** [comment]
I'm not using any setup, just using the depends argument to SharedJobCluster, to get the files there. And if they aren't in the correct place when the compute method runs, uses os.rename to put them in the right subdirectory (not the best way to do it, but there was only three files that needed to be transferred). I don't have any file handles open. 

I'll try to describe the error I'm having with module dependencies later.

**Comment by adam-douglass** [comment]
Turns out I just forgot the --daemon argument in my crontab. The unlinked file is probably the os buffer for the stdout.
