### ISSUE TITLE
dispy: crash when dispy ran as daemon in a docker

### ISSUE THREAD

**Issue by n0mik0s** [pgiri/dispy#36]
Hello!
I've tried to run dispy server process into a docker as a daemon. The result is:
TEST [root@bsm-test1 ~]# docker run --net=host -d 76e2985ab517 /usr/local/bin/dispynode.py -d -i 10.1.24.29
3e405e54b55e7681a1a59770ea2a8e413dd1491bdc01ba15f9a29ef644f65d5d
TEST [root@bsm-test1 ~]# top
top - 14:46:28 up 17 days,  5:37,  1 user,  load average: 0.56, 0.18, 0.06
Tasks: 221 total,   1 running, 220 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.2%us,  0.1%sy,  0.0%ni, 99.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  12190516k total,  2336568k used,  9853948k free,   232892k buffers
Swap:  2097148k total,        0k used,  2097148k free,  1694524k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
40800 root      20   0  281m  16m 4848 S 107.7  0.1   0:02.68 dispynode.py

Docker consume all available CPU time of one of virtual CPU. When I've tried do attach to the container I got this:
Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "cpus" to change CPUs used, anything else to get status:
Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "cpus" to change CPUs used, anything else to get status:
Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "cpus" to change CPUs used, anything else to get status:
Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "cpus" to change CPUs used, anything else to get status:
Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "cpus" to change CPUs used, anything else to get status:
Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "cpus" to change CPUs used, anything else to get status: Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt

As far I understood dispy where trying to start recursive and every time failed to start.

Did any of you faced with such kind of error and how you fixed it?

P.S. I found a workeraund that help me to start dispy in a container:
screen
docker run --net=host -it 76e2985ab517 /usr/local/bin/dispynode.py -d -p 51349 -i bsm-test1.sdab.sn
close putty
But this is not the right way...

**Comment by pgiri** [comment]
Can you give more details about your setup? Is the host running Linux? Or Windows (with docker machine)? Under Linux (Ubuntu), latest version of dispy and asyncoro, dispy works fine. Can you run any other daemon/service in your docker?

**Comment by n0mik0s** [comment]
That were 3 nodes in cluster:
- slaves: virtual machines, wmvare 5, RHEL 6.7
- server: virtual machine, wmvare 5, RHEL 7.2
docker on VMs - 1.7.1
docker image - xenial image from docker.io (latest)
dispy inside dockers - installed via pip3

Unfortunately the project is closed for now and the infrastructure was destroyed.
We stopped on the worckeround with screen and dispy in it.

**Comment by pgiri** [comment]
Closing this issue for now, as this is not reproducible (as mentioned above, I have tested with docker under Ubuntu). Reopen if/when you have details / can reproduce.
