### ISSUE TITLE
Nodes fail on a large set of jobs

### ISSUE THREAD

**Issue by shinigami1494** [pgiri/dispy#37]
I am running some machine learning algorithms on a fairly large dataset. For a particular test I need to run the algorithm 500 times. I am using dispy to distribute computation over my machine and another machine over the network. After approximately 100 runs the nodes start failing giving this message

/Users/Ahmed/Downloads/QSIURP2016/files/BR_C1_H/
2016-06-08 10:06:30 dispy - Failed to run job 4484926160 on 10.33.48.38 for computation testFile; removing this node

If I restart the node (not my script), the error re-occurs when a job is sent to it. However if I restart my script it starts working fine. I manually forced my script to begin computation from where the node failed and it worked fine so its not an issue of my script throwing errors.

My code:

` def learnAndTest(x, trainSet, testFiles, crossVal=False, f_res=None):
	global fitCluster1
	global fitCluster2
	global testFileCluster
	print "size:",x

	fitCluster1 = dispy.JobCluster(fit,[node1])
	fitCluster2 = dispy.JobCluster(fit,[node2])
	start_time = time.time()
	# args = [([2**x,2**x],[dataset_dir+"LectureHall.train", dataset_dir+"Bathroom.train"])]
	GMMs = learn([2**x]*4,trainSet)
	# print GMMs
	print x, ("--- %s seconds ---" % (time.time() - start_time))
	fitCluster1.close()
	fitCluster2.close()

	# testFileCluster classifies files
	testFileCluster = dispy.JobCluster(testFile,[node1,node2], depends=[score])
	start_time = time.time()
	acc = 0
	if crossVal:
		acc = testPerFile(testFiles, ["Bathroom","LectureHall","Office","Pantry"], GMMs, "crossVal", f_res)
	else:
		testPerFile(testFiles, ["Bathroom","LectureHall","Office","Pantry"], GMMs, "perFile_noOverlap_30CCs", f_res)
	print x, ("--- %s seconds ---" % (time.time() - start_time))
	testFileCluster.close()
	print acc
	return acc
`
this function is called for every run of the algorithm.

**Comment by pgiri** [comment]
See https://sourceforge.net/p/dispy/discussion/1771150/thread/272bc176/ for a similar issue and possible solutions.

**Comment by pgiri** [comment]
Closing this issue, as it is due to creating many jobs which take up memory on the client, not nodes.
