### ISSUE TITLE
Config files do not work for dispynode.py

### ISSUE THREAD

**Issue by jonasc** [pgiri/dispy#39]
I'm currently looking at dispy and I noticed that somehow the config files do not work. At least they don't work for me with python 3.5.

The problem lies in these lines: https://github.com/pgiri/dispy/blob/a1408f71e678aa3c0448c824a05d083e3a68ff32/py3/dispy/dispynode.py#L1591-L1593

The dictionary update means that all config file values are overwritten since all possible values are also present in the argparser structure (due to default settings).

A possible solution would be using a replacement for the argparser e.g. https://github.com/bw2/ConfigArgParse / https://pypi.python.org/pypi/ConfigArgParse.

**Comment by pgiri** [comment]
I believe above commit should fix this issue. Please confirm.

**Comment by jonasc** [comment]
The code looks good. I'll try it out later and let you know. Thanks!

**Comment by jonasc** [comment]
Please have a look at my PR. It fixes an issue I encountered when testing your changes.

**Comment by jonasc** [comment]
I have encountered some more issues while testing. Especially one I don't really understand.

55b1e92f09f07d24363d13be0419583cc78e1879 must introduce some subtle changes to the node changing its behavior. When I first checked out the repository with 533bd5e a new client connected to already running nodes.
Starting with commit 55b1e92f09f07d24363d13be0419583cc78e1879 this no longer works. If a node is already running the client just hangs as if no node were present. When restarting the node (or even just typing "stop" and "start") the client recognizes the node again and the computations are done.

I'll try to dig further in the offending commit but you might already see the problem?

**Comment by jonasc** [comment]
I found the offending line: https://github.com/pgiri/dispy/blob/55b1e92f09f07d24363d13be0419583cc78e1879/py2/dispy/dispynode.py#L1545
Setting the `node_port` to 0 causes the undesired behavior.

Maybe there need to me some more thought put into the config file options.
