### ISSUE TITLE
Version numbers mismatch

### ISSUE THREAD

**Issue by jonasc** [pgiri/dispy#49]
While trying to find the right commit for the versions you suggested in #48, I found out that your setup.py still has version `4.6.14` while the module has version `4.6.15`. You might want to have a look at https://pypi.python.org/pypi/bumpversion to avoid this in the future.
It would also be great to `git tag` the versions in the repository (which the bumpversion tool can do, too) to easily find them again.

**Comment by pgiri** [comment]
Sorry I have not been tagging releases. I have done this now (for 4.6.15) and will do for future releases as well.
