### ISSUE TITLE
Disypnode communication with the Scheduler timed out

### ISSUE THREAD

**Issue by albertorepo** [pgiri/dispy#50]
Hi Folks,

I have been running a mini-cluster with 2 nodes and a scheduler without problem until today.

Now, the node that is also running the shechuler is discovered without any problem.
However, the second node (differente machine and thus different IP address), is discovered but the PING connection times out everytime I run the dispynode.py.

Any advice here?

Thank you.

**Comment by lewisoshaughnessy** [comment]
Hi, what was the fix for this? I'm having very similar problems :-)
