### ISSUE TITLE
Enhnancement: More helpful error message when node is being ignored.

### ISSUE THREAD

**Issue by davet2001** [pgiri/dispy#53]
Hi, I have been using dispy for a task to perform ~50000 jobs which take ~30secs each.  Really finding it very helpful.  I have found that if there is a python version mismatch between the node and the client (using python 3.5 and 2.7), a message was shown on the client:

ignoring node xx ("secret" mismatch?)

This led me down a lot of wasted time with trying different secrets, encoding the secret in different ways, enclosing in quotations etc etc before I eventually modded the library and got it to generate the actual exception.

In __init__.py tcp_task() there is an assertion check on the secret, but all exceptions are caught and assumed to be this assertion failure.  When I modded the library I actually got a pickle protocol error, which was caused by the python version mismatch.

I propose the following patch (I will paste inline and also attach if I can figure out how to do it.):

```
diff --git a/py2/dispy/__init__.py b/py2/dispy/__init__.py
index 92d2680..1923dda 100644
--- a/py2/dispy/__init__.py
+++ b/py2/dispy/__init__.py
@@ -859,8 +859,10 @@ class _Cluster(object):
                                    info['ip_addr'], info['version'], _dispy_version)
                     raise StopIteration
                 assert info['auth'] == self.auth
-            except:
-                logger.warning('Ignoring node %s ("secret" mismatch?)', addr[0])
+            except (AssertionError):
+                logger.warning('Ignoring node %s ("secret" mismatch)', addr[0])
+            except (Exception) as err:
+                logger.warning('Ignoring node %s (%s: %s)', addr[0], err.__class__.__name__, err)
             else:
                 self.add_node(info)
 
diff --git a/py3/dispy/__init__.py b/py3/dispy/__init__.py
index b37420d..0d3fd1b 100755
--- a/py3/dispy/__init__.py
+++ b/py3/dispy/__init__.py
@@ -864,8 +864,10 @@ class _Cluster(object, metaclass=Singleton):
                                    info['ip_addr'], info['version'], _dispy_version)
                     raise StopIteration
                 assert info['auth'] == self.auth
-            except:
-                logger.warning('Ignoring node %s ("secret" mismatch?)', addr[0])
+            except (AssertionError):
+                logger.warning('Ignoring node %s ("secret" mismatch)', addr[0])
+            except (Exception) as err:
+                logger.warning('Ignoring node %s (%s: %s)', addr[0], err.__class__.__name__, err)
             else:
                 self.add_node(info)
```

**Comment by davet2001** [comment]
Adding patch file.
[dispy_secret_mismatch_improvement_2017-01-06_patch.txt](https://github.com/pgiri/dispy/files/691032/dispy_secret_mismatch_improvement_2017-01-06_patch.txt)

**Comment by pgiri** [comment]
Thanks. Applied the patch.
