### ISSUE TITLE
canonical example hangs Windows, python 2.7

### ISSUE THREAD

**Issue by luckjiff** [pgiri/dispy#55]
Hello - I tried running the canonical example (sample.py, 6.3. Canonical Program) on Windows 7 with python 2.7 and it is fails to return.  
My goal is to simply run my function multiple times on the same computer.
Maybe I should use the command line or python script interface instead?
Any hints on how I can proceed - Thanks!

**Comment by pgiri** [comment]
Likely network address detected/used by dispy is local address (127.0.0.1)? Giving correct address correctly with 'ip_addr' parameter may work.

**Comment by luckjiff** [comment]
Thanks. Works great!
