### ISSUE TITLE
Node crashes when configuring scheduler_node

### ISSUE THREAD

**Issue by yschroeder** [pgiri/dispy#59]
I try to configure a node to join an existing scheduler on the same network that has jobs in the queue. If I understood correctly, I can do this by starting the node with the `--scheduler_node` parameter and it should start working on jobs immediately. However, this results in the following error (which does not look like I am doing something wrong).

Or am I doing something wrong?

Full dump of dispynode.py:
```
$ ~/.local/bin/dispynode.py -d -s <secret> --scheduler_node=<scheduler_ip>

  "psutil" module is not available;
    node status (CPU, memory, disk and swap space usage) will not be sent to clients

2017-03-06 17:34:29 dispynode - dispynode version: 4.7.1, PID: 23792
2017-03-06 17:34:29 asyncoro - version 4.5.1 with epoll I/O notifier
2017-03-06 17:34:29 dispynode - "<hostname>" serving 16 cpus at <ip>:51348
2017-03-06 17:34:29 dispynode - tcp server at <ip>:51348
2017-03-06 17:34:29 dispynode - Traceback (most recent call last):
  File "/home/<user>/.local/bin/dispynode.py", line 419, in send_pong_msg
    scheduler_ip_addrs = info['ip_addrs']
KeyError: 'ip_addrs'


Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "cpus" to change CPUs used, anything else to get status: 2017-03-06 17:34:30 asyncoro - uncaught exception in ~tcp_serve_task/140660603299880:
Traceback (most recent call last):
  File "/home/<user>/.local/lib/python3.5/site-packages/asyncoro/__init__.py", line 3741, in _schedule
    retval = coro._generator.throw(*exc)
  File "/home/<user>/.local/bin/dispynode.py", line 975, in tcp_serve_task
    msg = yield conn.recv_msg()
  File "/home/<user>/.local/lib/python3.5/site-packages/asyncoro/__init__.py", line 3743, in _schedule
    retval = coro._generator.send(coro._value)
  File "/home/<user>/.local/lib/python3.5/site-packages/asyncoro/__init__.py", line 894, in _async_recv_msg
    raise socket.error(errno.EPIPE, 'Insufficient data: %s / %s' % (len(data), n))
BrokenPipeError: [Errno 32] Insufficient data: 0 / 1970038130
```

After that the node is running (but not doing any jobs). If I restart the scheduler then, it connects to the node normally.

**Comment by pgiri** [comment]
It seems it is due to node's own ping broadcast message coming back to itself causing pong reply to fail as it is not from scheduler. I will test and commit the fix likely tomorrow.

**Comment by yschroeder** [comment]
Ok thank you! I'll be available to test the fix.

**Comment by pgiri** [comment]
Just committed the fix. I haven't had much time to test it though.

**Comment by yschroeder** [comment]
The crash is gone, however the node does not connect to the already running scheduler. If I start the scheduler after the node (with the node's ip as `-n` parameter) it connects fine.

**Comment by pgiri** [comment]
Thanks for testing. Another fix committed.

I am wondering if your scheduler/node is on wireless, as it looks like UDP messages are being dropped or blocked.

Also, earlier errors didn't cause node to crash. With asyncoro, if a coroutine raises an exception that coroutine is thrown away but rest of the system continues to work (i.e., asyncoro is designed for fault-tolerance). So even earlier, if you restarted scheduler node would've worked fine.

**Comment by yschroeder** [comment]
I believe it works correctly now:
* start scheduler
* start node (with `--scheduler_node` option)
* scheduler discovers node
* stop node (input `exit`)
* start node
* scheduler rediscovers node

If you want to dive deeper into the issue with the UDP broadcast, I am waiting for an answer of our administrator. Maybe something happens with UDP broadcasts between those two machines. I can tell you though that none of them is on wireless. Both are in the same server room (but that does not mean anything...).

**Comment by yschroeder** [comment]
I confirmed with our administrator, that both machines are in different subnets and UDP broadcast is not possible between them.

I have another use case with dispyscheduler and dispynode that is not handled correctly currently. This is most likely not a bug but a feature request, so I will open another issue for this.

I believe this one is solved now.
