### ISSUE TITLE
cluster depends file/program transfer failure

### ISSUE THREAD

**Issue by wsfax** [pgiri/dispy#60]
I have a node which is running **on a different machine** than my client program.

When I try to add a file as dependency for my cluster, the node tries to copy it from the local path of the client machine.

I was expecting that dispy will serialize the content of the program and its dependencies and send the content over the network to nodes.

here is the error log:
```
2017-03-07 14:34:12 dispynode - dispynode version: 4.7.1, PID: 7452
2017-03-07 14:34:12 asyncoro - version 4.5.1 with IOCP I/O notifier
2017-03-07 14:34:12 dispynode - "RENDERER-01" serving 20 cpus at 192.168.13.61:51348
2017-03-07 14:34:12 dispynode - tcp server at 192.168.13.61:51348

Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "cpus" to change CPUs used, anything else to get status: 2017-03-07 14:34:18 asyncoro - uncaught exception in ~tcp_serve_task/51140480:
Traceback (most recent call last):
  File "C:\Miniconda2\lib\site-packages\asyncoro\__init__.py", line 3679, in _schedule
    retval = coro._generator.throw(*exc)
  File "C:\Miniconda2\Scripts\dispynode.py", line 991, in tcp_serve_task
    yield add_computation_task(msg)
  File "C:\Miniconda2\lib\site-packages\asyncoro\__init__.py", line 3681, in _schedule
    retval = coro._generator.send(coro._value)
  File "C:\Miniconda2\Scripts\dispynode.py", line 701, in add_computation_task
    compute.dest_path = tempfile.mkdtemp(prefix=compute.name + '_', dir=dest)
  File "C:\Miniconda2\lib\tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Temp\\new_d\\bin\\task.bat_jwjn5n'
```

and here the client code:
`
cluster = dispy.JobCluster('C:\\Temp\\new_d\\bin\\task.bat', depends=['C:\\Temp\\new_d\\bin\\cib.dll'])
`

**Comment by pgiri** [comment]
dispy will save files with absolute path names with same path name on nodes (so system files can be transferred). In this case, it looks like node(s) don't have directory 'C:\\Temp\\new_d\\bin' so saving 'task.bat' in that directory on node failed. You can either give relative path (e.g., copy 'task.bat' to directory where your client program is and give path as 'task.bat'), or create the directory on nodes.

**Comment by wsfax** [comment]
ok thanks for the explanation, I changed the path to task.bat to relative path and now it works fine. On the node machine they get copied to **dest_path_prefix/<node_ip>/task.bat_<uid>/**
is there a way to retrieve that path later on inside my computation function ?

**Comment by pgiri** [comment]
`os.getcwd()` in computation will give full path to the directory; i.e., computation's working directory is where files are saved.

**Comment by wsfax** [comment]
thanks.
