### ISSUE TITLE
Scheduler should have option to pass config file

### ISSUE THREAD

**Issue by yschroeder** [pgiri/dispy#65]
When using the scheduler on a multi user machine, the launch parameters (`cluster_secret` and `node_secret`) should be passed via a config file to the scheduler. Otherwise other users can see the secrets (`ps aux`) and run code on the cluster with the rights of the user who started the cluster.

Workaround is to use keyfiles and certificates instead of shared secrets, but using secrets and config files is a bit easier.

With the node this is not an issue as it already has the config file option.

**Comment by pgiri** [comment]
This is addressed in current github / 4.7.2 release.

**Comment by yschroeder** [comment]
There seems to be a bug here:
Dispyscheduler ignores nodes because of a "secret" mismatch.

Reproduction:
* `dispyscheduler.py --node_secret foobar --save_config scheduler.cfg`
* `dispyscheduler.py --config scheduler.cfg`
* `dispynode.py --secret foobar`

Error:
`2017-03-16 16:18:54 dispyscheduler - Ignoring node <IP> due to "secret" mismatch`

Working:
* `dispyscheduler.py --node_secret foobar`
* `dispynode.py --secret foobar`

**Comment by pgiri** [comment]
It seems I didn't apply another patch pending before 4.7.2 release. It is now committed and should fix the issue.

**Comment by yschroeder** [comment]
Works now, thanks.
