### ISSUE TITLE
Add function to kill a cluster

### ISSUE THREAD

**Issue by yschroeder** [pgiri/dispy#66]
I am currently trying to exit my program cleanly when hitting `ctrl+c`. What my program does is:

1. Add a bunch of jobs to a cluster
2. Wait for jobs to finish
3. Change some parameters based on the result and start over at 1

It is designed to run indefinitely as it will produce new results with every iteration. I want to kill the cluster at any point (if I want to change the code for debugging). What I currently do is when `ctrl+c` is pressed:

1. iterate over the list of jobs and call `cluster.cancel()` for those with status `Created` or `Running`
2. `cluster.wait()`
3. `cluster.close()`
4.  `sys.exit(0)`

As all of this is done in the `SIGINT` handler I have quite some race conditions with the normal program submitting new jobs and generally interacting with the cluster.

I propose to add a function `cluster.kill()` that does the following:
1. Stop handing new jobs to the scheduler 
2. Calls to `cluster.submit()` return `None`
3. Make all calls to `cluster.wait()` block indefinitely (to block other threads)
4. Cancel all jobs (with status `Created` or `Running`)
5. Block until everything is canceled
6. Close the cluster

This would allow to make a `SIGINT` handler with two lines of code:
1. `cluster.kill()`
2. `sys.exit(0)`

After writing all of this I belive most of this can be solved with the correct used of `threading.Lock()`... but maybe you find some inspiration here to help users exit their program cleanly.

**Comment by pgiri** [comment]
I have an implementation that addresses issue #64. I will commit probably tomorrow.

**Comment by yschroeder** [comment]
Yes, that might solve this problem as well.

**Comment by pgiri** [comment]
This is addressed in current github / 4.7.2 release.

**Comment by yschroeder** [comment]
Thanks! It works in general, but there is still a bug left:

`cluster.close(terminate=True)` blocks and waits for all submitted jobs to terminate and also allows pending jobs to start (same as close without terminate I belive). `cluster.close(timeout=0, terminate=True)` works as expected (waits zero seconds and then kills all jobs on the workers).

**Comment by pgiri** [comment]
Default timeout is `None` which will wait for all jobs to finish before terminating. As you mentioned, passing timeout as 0 or some positive number should work as expected.
