### ISSUE TITLE
dispyscheduler has dependency for module six

### ISSUE THREAD

**Issue by yschroeder** [pgiri/dispy#67]
A fresh installation of dispy crashes when starting dispyscheduler.

Reproduction:
* `git clone https://github.com/pgiri/dispy.git`
* `cd dispy`
* `python3 setup.py install --user`
* `~/.local/bin/dispyscheduler.py`

Error:
```
Traceback (most recent call last):
  File "/home/<user>/.local/bin/dispyscheduler.py", line 4, in <module>
    __import__('pkg_resources').run_script('dispy==4.7.2', 'dispyscheduler.py')
  File "/home/<user>/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 48, in <module>
    import six
ImportError: No module named 'six'
```

Fix:
* `pip3 install six --user`

**Comment by pgiri** [comment]
Neither dispy nor asyncoro use module 'six' and so closing this issue. I am guessing this may be related to 'pkg_resources'.
