### ISSUE TITLE
Fails on a system with an ipv6 address

### ISSUE THREAD

**Issue by t-animal** [pgiri/dispy#69]
When run on a system with an ipv6 address dispy fails:

```
$> dispynode.py 

  "psutil" module is not available;
    node status (CPU, memory, disk and swap space usage) will not be sent to clients

2017-03-21 15:44:57 dispynode - dispynode version: 4.7.3, PID: 30300
Traceback (most recent call last):
  File "/home/tilman/Uni/sem_03/MA/code/venv/bin/dispynode.py", line 1885, in <module>
    _dispy_node = _DispyNode(**_dispy_config)
  File "/home/tilman/Uni/sem_03/MA/code/venv/bin/dispynode.py", line 222, in __init__
    self.addrinfo = dispy.node_addrinfo(ip_addr)
  File "/home/tilman/Uni/sem_03/MA/code/venv/bin/dispy.py", line 305, in node_addrinfo
    socket_family = socket.getaddrinfo(socket.gethostbyname(socket.gethostname()), None)[0][0]
socket.gaierror: [Errno -2] Name or service not known
```

This is because socket.gethostbyname does not support ipv6. When passed an ipv4 address via the "-i" parameter it works, however that makes running it a lot more problematic

**Comment by pgiri** [comment]
Committed d274064..4f163ce that should address this issue, although not tested with IPv6. Please test and confirm if it works or not.

**Comment by t-animal** [comment]
I've tested the commited lines and they don't throw. However mysteriously neither do the original ones currently (even though I do have an IPv6 address, but that's on a different computer with a different linux distro, so maybe some configuration is different). I'll have to try again when I'm on the network where it threw and that'll only be next Tuesday...

**Comment by pgiri** [comment]
Can you update if you had a chance to test? I am hoping to release next version with this fix.

**Comment by t-animal** [comment]
No, sorry. In the end I needed something simpler than dispy an wrote it 
myself. Therefore I forgot testing on Tuesday. However I've written myself 
a reminder and will try coming Tuesday.

**Comment by t-animal** [comment]
Mhm, it still fails, but differently now.

```
$ dispynode.py 

  "psutil" module is not available;
    node status (CPU, memory, disk and swap space usage) will not be sent to clients

2017-04-04 17:14:49 dispynode - dispynode version: 4.7.3, PID: 19455
Traceback (most recent call last):
  File "/var/tmp/venv/bin/dispynode.py", line 1885, in <module>
    _dispy_node = _DispyNode(**_dispy_config)
  File "/var/tmp/venv/bin/dispynode.py", line 222, in __init__
    self.addrinfo = dispy.node_addrinfo(ip_addr)
  File "/var/tmp/venv/bin/dispy.py", line 305, in node_addrinfo
    socket_family = socket.getaddrinfo(socket.gethostname(), None)[0][0]
  File "/usr/lib64/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by pgiri** [comment]
That seems to be an issue with name resolution. If you run `socket.gethostname()` with Python and then run `host` command on the name, it should resolve to IPv6 address. If not, either host name or DNS is setup incorrectly.

**Comment by t-animal** [comment]
You're right, it fails on this network in particular. I didn't expect that it might be set up incorrectly as it is maintained by a big contractor.
