### ISSUE TITLE
Node information page throws an exception when using dispyscheduler

### ISSUE THREAD

**Issue by capt-underpants** [pgiri/dispy#73]
Trying to view the node information page for a specific machine on the HTTP server started
when passing "--httpd" to dispyscheduler.py results in the following exception:

```
File "<site_packages_dir>/dispy-4.7.4-py2.7.egg/dispy/httpd.py", line 207, in do_POST
  for job in cluster_jobs])
AttributeError: '_DispyJob_' object has no attribute 'id'
```

As a result the page displays a "Node update failed." message.

I am using a modified version of "httpd_example.py" to start a SharedJobCluster:
```python
class C(object):
    def __init__(self, s, i):
        self.s = s
        self.i = i
    # provide __str__ so instances of C are shown with useful info
    # when monitoring jobs in 'Node' page
    def __str__(self):
        return 'C(%s, %.4f)' % (self.s, self.i)

def compute(obj, n=5):
    # obj is an instance of C
    import time
    time.sleep(n)
    return n * obj.i

if __name__ == '__main__':
    import dispy, random

    # create cluster
    cluster = dispy.SharedJobCluster(compute, depends=[C],
                                     scheduler_node='machine_2',
                                     nodes=['machine_1', 'machine_2'])

    for i in range(8): # submit jobs to cluster
        c = C(str(i), random.uniform(1, 9))
        job = cluster.submit(c, n=random.randint(5, 20))
        job.id = i

    cluster.wait() # wait for all jobs to finish
    cluster.close()
```

The scheduler is started on machine_2 using the command:
```dispyscheduler.py --httpd --clean```

dispynode.py is started on machine_1 and machine_2 using the command:
```dispynode.py --clean```

The script is ran from machine_1.

Is it possible to view this information when the HTTP server has been started from a scheduler?

**Comment by pgiri** [comment]
Thanks for reporting the issue. It is now fixed.
