### ISSUE TITLE
Compatibility for Python3.5

### ISSUE THREAD

**Issue by petroniocandido** [pgiri/dispy#79]
Hello,

First of all congrats for this excellent tool!

I was working on a cluster with 3 machines running on Ubuntu 16.04 and Python 3. Few days ago I've moved all machines to Kubuntu 17.04 that has only the Python 3.5. The dispy is installed with the most recent version (also pycos). The problem is when I start a cluster and just the dispynode on local machine receive the jobs. On http server also the other machines did not appear.  I double checked the configurations and code and it is ok. This can be a Python version compatibility problem?

Thanks in advance!

**Comment by pgiri** [comment]
I just tested with python3.5; it worked fine with 2 nodes. With your setup, make sure the IP address used by dispynode is appropriate network address (and not '127.0.0.1'). You may want to install 'netifaces' package on the nodes - dispy may be able to detect appropriate interface address with 'netifaces'. Another possibility is firewall may be preventing ports used by dispy (UDP and TCP ports 51347 to 51350).

**Comment by petroniocandido** [comment]
Hello Giridhar! Thank you for the quick answer!

I'm trying with two nodes: 192.168.0.106 and 192.168.0.110 (on this last one I'm starting the cluster and http server). Both computers ping each other and there are no rules on firewall (tested with the command sudo iptables -L)
I've noted something really strange on node 192.168.0.106. I use the following command to start the dispynode:

sudo python3 /usr/local/bin/dispynode.py -i 192.168.0.106 -d

And the output was:

2017-07-15 16:23:12 dispynode - dispynode version: 4.8.2, PID: 11036
2017-07-15 16:23:12 pycos - version 4.6.1 with epoll I/O notifier
2017-07-15 16:23:12 dispynode - "pc-notebook" serving 4 cpus
2017-07-15 16:23:12 dispynode - TCP server at 192.168.0.106:51348

Enter "quit" or "exit" to terminate dispynode,
  "stop" to stop service, "start" to restart service,
  "cpus" to change CPUs used, anything else to get status: 

But when a use the command "netstat | grep 51348" nothing is shown.  I did exactly the same test with the other machine and it show the dispynode processes binded with the address. 

Both machines has the same OS (KUbuntu 17.04) but I'm suspecting that in the first machine some lib is missing. Can you imagine something?

**Comment by pgiri** [comment]
By any chance one or both of them using WiFi? With WiFi, UDP may be lossy. Can you try adding 'nodes=["192.168.0.106"]' to dispy.JobCluster. Explicitly listed nodes are discovered with TCP and thus should work. 

Default 'netstat' won't list all ports; instead, use 'netstat -na | grep 51348'.

**Comment by petroniocandido** [comment]
Wow.... I don't know what happened but now it is working! Thank you for the attention and patience!

Once again, congrats for this wonderful tool!
