### ISSUE TITLE
External IP address with dispynode

### ISSUE THREAD

**Issue by CodyRude** [pgiri/dispy#80]
I'm receiving a TypeError when using an external address with dispynode in 4.8.2.

```
dispynode.py --ext_ip_addr 10.83.1.15
2017-07-24 10:00:33 dispynode - dispynode version: 4.8.2, PID: 3277
Traceback (most recent call last):
  File "/Users/cmrude/anaconda/envs/python36/bin/dispynode.py", line 1918, in <module>
    _dispy_node = _DispyNode(**_dispy_config)
  File "/Users/cmrude/anaconda/envs/python36/bin/dispynode.py", line 245, in __init__
    ext_ip_addr = ext_ip_addr[1]
TypeError: 'AddrInfo' object does not support indexing
```

It works fine in 4.8.1

**Comment by pgiri** [comment]
Sorry about that. `node_addrinfo` function has been changed in 4.8.2 to return a named tuple instead of tuple. It seems I didn't fix all the places where it is used. Will commit a fix soon.

**Comment by pgiri** [comment]
Can you test current git tree (or you can just download [dispynode.py](https://raw.githubusercontent.com/pgiri/dispy/master/py2/dispy/dispynode.py)) and confirm if it works or not?

**Comment by CodyRude** [comment]
I installed from the git repo and dispynode.py starts up properly. Thanks!
