### ISSUE TITLE
Cannot use multiple clusters in multiple threads

### ISSUE THREAD

**Issue by li-ji** [pgiri/dispy#81]
When I submitted many jobs via cluster.submit() each of which contains huge input data, cluster.submit() takes a lot time. In order to reduce the submission wall time, I tried to submit those jobs in different threads but failed.

I launched 4 dispynode.py processes on 4 different servers with different node_ports and different ports. In mt_example.py, I created 4 JobCluster objects each of which uses corresponding node_ports and ports as previous launched dispynode.py processes.

4 dispynode.py processes launching commands:
$ dispynode.py -d --secret=0731 -i 10.91.19.30 --node_port=8340 --scheduler_port=8640 --dest_path_prefix=$HOME/xxx --clean
$ dispynode.py -d --secret=0731 -i 10.91.107.11 --node_port=8341 --scheduler_port=8641 --dest_path_prefix=$HOME/xxx --clean
$ dispynode.py -d --secret=0731 -i 10.91.16.6 --node_port=8342 --scheduler_port=8642 --dest_path_prefix=$HOME/xxx --clean
$ dispynode.py -d --secret=0731 -i 10.91.113.9 --node_port=8343 --scheduler_port=8643 --dest_path_prefix=$HOME/xxx --clean

As a result, only one of the dispynode.py processes can be connected. All above ports are opened in the firewall.

Is it possible to use multiple clusters in multiple threads? Actually different cluster manages different set of nodes. The only purpose is to reduce the cluster.submit() wall time when input data is huge.

Following are the output.

$ python mt_example.py
Create clusters
['10.91.19.30', '10.91.107.11', '10.91.16.6', '10.91.113.9'] [8340, 8341, 8342, 8343] [8640, 8641, 8642, 8643]
2017-08-10 13:30:54 pycos - version 4.6.1 with epoll I/O notifier
2017-08-10 13:30:54 dispy - dispy client version: 4.8.3
2017-08-10 13:30:54 dispy - Storing fault recovery information in "_dispy_20170810133054"
Create test data
Prepare data list for multi-threads run
Start mutiple clusters in multi-threads
_submit_and_run()@10.91.19.30: Dispy submit wall time: 1.402 seconds.
_submit_and_run()@10.91.16.6: Dispy submit wall time: 1.400 seconds.
_submit_and_run()@10.91.107.11: Dispy submit wall time: 1.859 seconds.
_submit_and_run()@10.91.113.9: Dispy submit wall time: 1.631 seconds.
0 302893640
1 302893640
2 302893640
3 302893640
4 302893640
5 302893640
6 302893640
7 302893640
_submit_and_run()@10.91.19.30: Dispy total wall time: 7.437 seconds.

Then hanges forever because only one of 4 clusters can gets and runs jobs. Other clusters cannot connect any nodes allocated for them.

```
# mt_example.py
import timeit
import threading

def compute(data):
    import time
    time.sleep(5)
    return sum([sum(a) for a in data])


def _submit_and_run(cluster, node, args):
    assert isinstance(cluster, dispy.JobCluster)
    jobs = list()
    t1 = timeit.default_timer()
    for i, data in enumerate(args):
        # submit huge data may take some time
        #job = cluster.submit_node(node, c, data) # it is sent to a node for executing 'compute'
        job = cluster.submit(data) # it is sent to a node for executing 'compute'
        job.id = i # store this object for later use
        jobs.append(job)
    t2 = timeit.default_timer()
    print("_submit_and_run()@%s: Dispy submit wall time: %.3f seconds." % (node, t2 - t1))
    for job in jobs:
        job() # wait for job to finish
        print(job.id, job.result)
    t3 = timeit.default_timer()
    print("_submit_and_run()@%s: Dispy total wall time: %.3f seconds." % (node, t3 - t1))

if __name__ == '__main__':
    import random, dispy
    print("Create clusters")
    nodes=['10.91.19.30','10.91.107.11','10.91.16.6','10.91.113.9']  # you may change to your IPs
    node_ports=[8340 + i for i in range(len(nodes))] # you may change to your own node_ports
    ports=[8640 + i for i in range(len(nodes))] # you may change to your own ports
    print(nodes, node_ports, ports)
    clusters = dict()
    for idx, node in enumerate(nodes):
        clusters[node] = dispy.JobCluster(compute,
                nodes=node,
                ip_addr='10.91.19.30',  # you may change to your own IP
                secret='0731',
                node_port=node_ports[idx],
                port=ports[idx])

    print("Create test data")
    huge_data = [[random.randint(1, 100) for j in range(600)] for i in range(10000)]

    print("Prepare data list for multi-threads run")
    num_tasks = 32
    data = dict()
    for node in nodes:
        data[node] = list()
    i = 0
    assert num_tasks > 0
    while i < num_tasks:
        for node in nodes:
            data[node].append(huge_data)
            i += 1;
            if i >= num_tasks:
                break  # for

    print("Start mutiple clusters in multi-threads")
    # Following multi-thread will hange because some clusters won't connected any nodes.
    # All jobs submitted to the clusters will keep pending.
    threads = list()
    for node in nodes:
        thread = threading.Thread(target=_submit_and_run, args=(clusters[node], node, data[node],), name='Thread-%s'%node)
        threads.append(thread)
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    print("Close all clusters")
    for node, cluster in clusters.items():
        cluster.print_status()
        cluster.close()

```

**Comment by li-ji** [comment]
Maybe I can pass write the huge data to a binary file and then transfer the file before calling cluster.submit(). cluster.submit() will only pass a few data.
The file contains huge data can be transferred to every node in parallel, for example in multi-thread. The file will be shared among workers in the same node.
I guess the wall time of cluster.submit() and data file transferring will be reduced. I will try this and post my test results later.

**Comment by pgiri** [comment]
Submitting jobs with threads wouldn't improve performance. In fact, as mentioned on [pycos](https://pycos.sourceforge.io) page, using threads to improve CPU usage is actually counter-productive, as Python executes at most one thread at any time (and due to context switching, it is likely that more threads are worse than one thread).

Two things that are expensive in creating jobs are: Serializing job arguments and generating random ID for job (using `os.urandom`). I don't see any good way to speed them up (either in dispy or in the client). There are no threading synchronizations involved in that path (or elsewhere in dispy, for that matter), as pycos is used (pycos's previous incarnation asyncoro was actually developed to avoid issues with threads in Python).

I am wondering if this concern (submitting jobs is expensive) is really an issue in real world: If dispy scheduler is waiting for jobs to finish; i.e., after a while all available nodes are busy computing and submitting more jobs at the client shouldn't affect observed performance as the scheduler is waiting for scheduled jobs to finish before it can submit another job. As in the above example, you may notice submitting jobs is expensive until all available CPUs are used up, but after that it shouldn't be an issue (unless of course job arguments are too big).

As for why using multiple threads doesn't recognize all available nodes, I don't know. There may be potential issues in dispy's job submission that don't expect multiple threads executing it!

**Comment by pgiri** [comment]
Yes, if there is a way to transfer data to nodes ahead (either with dispy's `send_file` method, or nodes accessing file over NFS, say), then submitting jobs should be very efficient. You may also want to look at splitting the data so each node has access to part of the data used for jobs on that node. And if the cluster is used exclusively, then you can use `dest_path` and set `cleanup=False` if it is likely that you want to run multiple experiments on the data so that data is transferred once and later experiments can reuse the data transferred once. If you use this approach you may want to run a dummy computation with `cleanup=True` at the end to remove all files transferred (or files can be removed manually on each node, which can be cumbersome).

**Comment by pgiri** [comment]
It seems to me it is possible that same (huge) data may be submitted to a node more than once (unless each node executes one job), which may be the reason for poor performance. Simplest solution is to send data in `depends` when creating cluster, so dispy will send it to each node once and job submission should be quick. Alternately, you can use `send_file` as mentioned above.

**Comment by li-ji** [comment]
Hello @pgiri ,

Thanks a lot for the quick response.

Multiple clusters didn't recognize the nodes allocated no matter using multi-thread or not. It seems a different issue from the multi-thread topic.

Following piece of code with single thread can reproduce the issue:
```
if __name__ == '__main__':
    import random, dispy
    print("Create clusters")
    nodes=['10.91.19.30','10.91.107.11','10.91.16.6','10.91.113.9']  # you may change to your IPs
    node_ports=[8340 + i for i in range(len(nodes))] # you may change to your own node_ports
    ports=[8640 + i for i in range(len(nodes))] # you may change to your own ports
    print(nodes, node_ports, ports)
    clusters = dict()
    for idx, node in enumerate(nodes):
        clusters[node] = dispy.JobCluster(compute,
                nodes=node,
                ip_addr='10.91.19.30',  # you may change to your own IP
                secret='0731',
                node_port=node_ports[idx],
                port=ports[idx])
```

Then only `clusters['10.91.19.30'].submit()` works. Rest clusters, for example `clusters['10.91.107.11'].submit()`, will hang forever because no node is connected to it. You may use `dispy.httpd.DispyHTTPServer(clusters['10.91.107.11'])` to check out that there is no node connected to the cluster.

However, if all nodes are allocated to one cluster, every node will be connected and jobs can be executed on every nodes. 

Is it possible to use several clusters in one single thread program? Each of the clusters has different `nodes`, different `node_port` and `port` and maybe different `secret`

**Comment by pgiri** [comment]
Yes, you can partition your nodes in to multiple clusters, but you have to specify which nodes are allocated to which clusters. This can be done with `nodes` in multiple ways. For example,::

    clusters = []
    for node in nodes:
        clusters.append(dispy.JobCluster(compute, nodes=[node], ...)

where `nodes` is list of IP addresses as above. You can also use wildcards etc. Default is `*` which matches any IP address (so all available nodes are allocated to a cluster). You can also customize nodes / CPUs using `NodeAllocate` class.

**Comment by li-ji** [comment]
In my case, there are 4 nodes each of which has 8 workers. 32 jobs are submitted to the 32 (4 nodes * 8 workers/node) workers so submit() doesn't have to wait for any scheduled jobs. Therefore the `submit` performance degeneration is due to the job input arguments. In my test when the input arguments are shorted, the `submit` wall time will be shorted in linear.

If the huge input data is passed by file, the expensive operations becomes the file read/write and network transmission. Then I guess multiple threads should improve the I/O performance unless the file read/write and network transmission operations exceed the disk and network hardware throughput.

Reusing input data must be helpful. Unfortunately I can only share input files among workers in the same node and the input file may be refreshed frequently because my jobs are submitted and run time and time again in iterations. The input file will be refreshed at the beginning of each iteration and then jobs are submitted and run with the input file and so forth. And I cannot split the input file because every job has to use the whole input data.

Thanks for providing the the approach for cleaning up files using dummy computation with `cleanup=True`. It is really useful.

**Comment by li-ji** [comment]
OK. I will try your approach to partition nodes in to multiple clusters.

My code may have a bug as follows:
```
dispy.JobCluster(compute, nodes='10.91.19.30', ...)
```
where `nodes` is an IP address instead of a list of IP address.

It seems that I should use following code instead:
```
dispy.JobCluster(compute, nodes=['10.91.19.30'], ...)
```

**Comment by li-ji** [comment]
I tested following two approaches:
1. Transferring huge input data by file and share the files among workers in the same node. It helps with `submit` efficiency. `send_file` and `JobCluster`'s `depends` list are useful.
2. Compressing huge input data before submitting them to node with `submit`.
Both worked in my case to reduce the `submit` wall time.
