### ISSUE TITLE
Starting dispynode.py on many servers

### ISSUE THREAD

**Issue by chazshapiro** [pgiri/dispy#87]
Hi, this is not really an issue with the code, just some questions about implementation.

1)  If I start dispynode.py on a host, is there a way for all users to send jobs to it rather than start their own servers?  My needs are simple - I just want it running all the time and accessible by anyone without them having to mess with it.

2)  I am trying to determine a convenient way to get dispynode.py started on many hosts.  I have a script that loops over the hosts (node1, node2, node3...) and sends an ssh command to start the server:

`ssh node$k "nohup python $dispypath/dispynode.py --clean --daemon >dispynode_output.log &"`

which is successful for me, but other users mysteriously can't get it working.  Is there a better way to do this?  Any obvious pitfalls?

**Comment by pgiri** [comment]
1. Yes, dispynode on your server can be used by other users. However, at a time only one client is served by a node. Once one client is done, dispynode runs jobs for another client. You may also want to look at SharedJobClusster if you want to run more than one client simultaneously.

**Comment by chazshapiro** [comment]
Thanks for the response.  How do I make dispynode visible to all users when I run it from my own account on the host?

For 2) I am actually asking a bash question -- what is the proper way to start dispynode on many hosts using a local command?

**Comment by pgiri** [comment]
dispynode is available for any dispy client running on local network. If you start dispynode with `secret` or SSL, then users need to use same parameters in the client programs.

dispynode can't be started on nodes using a command on local computer. At least, not with standard applications. The usual approach is to login to each node (e.g., with ssh) and run dispynode (and leave it running). Alternately, dispynode can be started as a daemon with system startup files.

**Comment by pgiri** [comment]
Is this still an issue? If not, can you close it?

**Comment by UnitedMarsupials** [comment]
It would've been good, if dispy had a sample service-script for "SysV" systems as well as for `systemd` based ones. @chazshapiro is not the only one having to implement it - many adopters would benefit...
