### ISSUE TITLE
dispyscheduler.py and dispy.SharedJobCluster can not run on the same machine

### ISSUE THREAD

**Issue by walachey** [pgiri/dispy#90]
When running a _dispyscheduler.py_ and trying to connect to it via _dispy.SharedJobCluster_ ON THE SAME MACHINE, the latter hangs indefinitely. The log of the scheduler prints the following (substituted real IP):

> dispyscheduler - Invalid message from XXX.XX.XXX.XX:56082 ignored

We can reproduce that on different machines. We tested Python 3.4.2 and 3.6.3.

More Information:
The scheduler is started with `dispyscheduler.py -i foobar.imp.fu-berlin.de`, the client tries to connect via 
`cluster = dispy.SharedJobCluster(compute, nodes=['*'], scheduler_node='foobar.imp.fu-berlin.de')`. The client is running on the same machine.
It works when I use _JobCluster_ and _dispynode.py_ directly.
It also works when I connect with _dispy.SharedJobCluster_ from a different machine.

Is there any reason why one computer cannot run both the scheduler and the SharedJobCluster?
We tried different combinations of ip_addr and also tried port=0 and other ports in the _dispy.SharedJobCluster_.

The scenario we have is that we have a hand full of computers that we use for calculations. Users generally also work on these computers (inside docker environments). So we would use computer 1 as the scheduler, the other computers AND computer 1 as nodes. Clients would connect to computer 1 (possibly also FROM computer 1) and use SharedJobCluster to start jobs.

Thanks!

**Comment by pgiri** [comment]
dispyscheduler and client (and dispynode, if desired) can be running on same machine, as they all use different ports. The only change needed when using dispyscheduler and client on same machine is to use `port=0` to `SharedJobCluster` as you mention. If you are having issues with this, it is likely you may have firewall issue (e.g., preventing port 51349, used by dispyscheduler). Or the IP address used by dispyscheduler doesn't match `scheduler_node` option to `SharedJobCluster`.

**Comment by walachey** [comment]
I tried the different combinations again:
The dispyscheduler is listening on port 51347 (`2017-11-09 11:20:39 dispyscheduler - TCP server at 160.XX.XXX.XX:51347`) and on 51349 (`2017-11-09 11:20:39 dispyscheduler - Scheduler at 160.XX.XXX.XX:51349`).

When I use the port 51347
----------------------------
`cluster = dispy.SharedJobCluster(compute, nodes=['*'], scheduler_node='foobar.imp.fu-berlin.de', scheduler_port=51347, port=0)`
The **SharedJobCluster** hangs a bit and then throws a `EOFError: Ran out of input` in `~/venvtest/lib/python3.4/site-packages/pycos/__init__.py in deserialize(pkl)` in line `74     return pickle.loads(pkl)`.
The **dispyscheduler** prints
`2017-11-09 11:21:38 dispyscheduler - Invalid message from 160.45.109.25:41842 ignored`

When I use the port 51349 (!)
----------------------------
`cluster = dispy.SharedJobCluster(compute, nodes=['*'], scheduler_node='foobar.imp.fu-berlin.de', scheduler_port=51349, port=0)`

The **SharedJobCluster** prints
>2017-11-09 11:30:23 pycos - version 4.6.4 with epoll I/O notifier
>2017-11-09 11:30:23 dispy - dispy client version: 4.8.3
>2017-11-09 11:30:23 dispy - Storing fault recovery information in "_dispy_20171109113023"

and then **hangs**.

When I interrupt it, it waits in
`~/venvtest/lib/python3.4/site-packages/dispy/__init__.py` in line `-> 2766             self._scheduled_event.wait()`

The **dispyscheduler** prints
>2017-11-09 11:30:23 dispyscheduler - New computation 140359883842224: compute, /tmp/dispy/scheduler/160.XX.XXX.XX/compute_2jyjrokr
>2017-11-09 11:30:23 dispyscheduler - Ignoring computation compute / 140359883842224 from 160.XX.XXX.XX:55025

When I use a different port
----------------------------
`cluster = dispy.SharedJobCluster(compute, nodes=['*'], scheduler_node='foobar.imp.fu-berlin.de', scheduler_port=51350, port=0)`
I quickly get a `ConnectionRefusedError: [Errno 111] Connection refused`, as expected.


So I don't think it is a connection or firewall issue. The SharedJobCluster can connect but never terminates the connection attempt. And the dispyscheduler seems to ignore the client?
Do you have any ideas how to further debug that?

**Comment by pgiri** [comment]
I have just tested with Python 3.6.3 and the only issue is a warning when client program is terminating (when a cluster is closed). Otherwise it works fine.

Can you run dispyscheduler with debug (with `-d` option) and `SharedJobCluster` with `loglevel=dispy.logger.DEBUG`? That may show useful information.

**Comment by walachey** [comment]
The above with _ignoring computation_ was already the debug output of the `dispyscheduler`. Without it, the `dispyscheduler` is completely silent. And the `SharedJobCluster` prints
>4.8.3
2017-11-09 14:20:42 pycos - version 4.6.4 with epoll I/O notifier
2017-11-09 14:20:42 dispy - dispy client version: 4.8.3
2017-11-09 14:20:42 dispy - Storing fault recovery information in "_dispy_20171109142042"
2017-11-09 14:20:42 dispy - Scheduler quitting: 0
2017-11-09 14:20:42 dispy - Scheduler quit
2017-11-09 14:20:42 dispy - dispy client at 127.0.1.1:38537

..and still hangs. This is the complete code, if it helps:
```
import dispy
print (dispy.__version__)

def compute(x):
    return x + 1

cluster = dispy.SharedJobCluster(compute, nodes=['*'], scheduler_node='foobar.imp.fu-berlin.de', scheduler_port=51349, port=0, loglevel=dispy.logger.DEBUG)
```
And the scheduler is launched with `dispyscheduler.py -i foobar.imp.fu-berlin.de -d`

**Comment by pgiri** [comment]
It seems client is starting at 127.0.01 instead of foobar.imp.fu-berlin.de. Can you include 'ip_addr=foobar.imp.fu-berlin.de` parameter to `SharedJobCluster` and try?

**Comment by walachey** [comment]
Yes, thank you. This seems to work!
It's odd that the loopback address fails silently but the real hostname works.

The working setup is now
`dispyscheduler.py -i foobar.imp.fu-berlin.de` and `dispynode.py --scheduler_node=foobar.imp.fu-berlin.de --clean` on the same machine.
And then (also from the same machine)
`cluster = dispy.SharedJobCluster(compute, nodes=['*'], scheduler_node='foobar.imp.fu-berlin.de', scheduler_port=51349, ip_addr='foobar.imp.fu-berlin.de', port=0)`

In case someone else has this problem. Thank you for your support, I'm going to close this issue :)

**Comment by pgiri** [comment]
This is usually due to network configuration on that computer. To fix this, set hostname (foobar.imp.fu-berlin.de) in`/etc/hostname` and update `/etc/hosts` so that hostname has correct address (160.x.x.x). Then dispy (and dispyscheduler, dispynode) should work without having to specify hostname.
