### ISSUE TITLE
Is that possible to run multiple server and a client in one machine?

### ISSUE THREAD

**Issue by qzshadow** [pgiri/dispy#93]
Hi, 
Now, I only have my laptop to do some experiments, I can run a Client by setting ip_addr to 127.0.0.1, with default port 51347, and simultaneously, I can run a Server by setting ip_addr to 127.0.0.1, with default port 51348, this configuration works well in toy examples.
When I try to run another Server by setting ip_addr to 127.0.0.1, with port 51349, I get an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/dispynode.py", line 1921, in <module>
    _dispy_node = _DispyNode(**_dispy_config)
  File "/usr/local/bin/dispynode.py", line 276, in __init__
    config.get('pid', None))
Exception: Another dispynode server seems to be running with PID 50482;
    terminate that process and rerun with "clean" option
```
Seems from the error, I only can run a server on my laptop, is that possible to run multiple server on my laptop? Thanks for any advice!

**Comment by pgiri** [comment]
A node may run only one dispynode at a time, as one dispynode manages all detected processors. If you run another instance, it will exit with the above message.

You can run multiple clusters in a single client program but not multiple `JobCluster` clients (you can technically run more than one client on same machine, but all but one would be able to use nodes; others will wait until currently running client finishes). Alternately, you can use dispyscheduler and `SharedJobCluster`, in which case multiple clients can be running (either on same machine or on another machine).
