### ISSUE TITLE
dispy hanging application from exiting?

### ISSUE THREAD

**Issue by joelcomp1** [pgiri/dispy#94]
I used to use the python multiprocessing library prior to using dispy so never saw this issue before but now sometimes at the end of main my program will just hang forever.  I am assuming some dispy processes/threads didn't exit or clean up successfully.  I am using cluster.wait() and cluster.close() with terminate = True and I don't see anything in any of my logs to indicate any of my jobs failed/threw a exception.  Also don't see dispy waiting a long time for jobs to finish/timing out.  

Not sure if there is any other things I can look at or other configuration I can use to force it to close everything and move on?

**Comment by pgiri** [comment]
Even if a job failed, dispy should work fine. You can use either `status` callback or httpd to monitor status of jobs. Or you could call `print_status` method periodically (this produces verbose output but easier to implement).

**Comment by joelcomp1** [comment]
Hmm very strange i am using the print_status call after each usage to get latency info and ensure everything is working successfully. I use 4 or 5 different clusters throughout my application and all return fine but hangs at the end occasionally.   I can get it to exit if I do a os._exit(0) though which makes me think it's a threading thing

**Comment by pgiri** [comment]
Is it possible to replicate this with a simple example that you can post / email? Also mention version of dispy and pycos you are using, along with OS used (on the client at least).

**Comment by joelcomp1** [comment]
haven't been able to reproduce it in a simplified way....if I can I will reopen Thanks for the ideas!
