### ISSUE TITLE
dispynode: 127.0.1.1 seems to be loopback address

### ISSUE THREAD

**Issue by orwel1984** [pgiri/dispy#98]
I have three nodes. 
On two of these I run the dispynode.py command and it works fine and they can communciate to each other. On the third node, i see a message like below: 

2017-12-15 10:17:55 dispynode - node IP address 127.0.1.1 seems to be loopback address; this will prevent communication with clients on other machines. 
2017-12-15 10:17:55 pycos - version 4.6.5 with epoll I/O notifier
2017-12-15 10:17:55 dispynode - TCP server at 127.0.1.1:51348

Note the 127.0.1.1 instead of the actual ip address. 
Then i can only run the local jobs on this machine but the other nodes cannot seem to find this node.

I can ping on the commandline between these machines. But the dispy does'nt see it at all.
The configuration on this machine is similar to other machines, same python and pip versions and hostname setup in /etc/hosts and /etc/hostname

Please help me solve this somehow.

**Comment by pgiri** [comment]
`-i` option can be used to give different address,e.g., as `dispynode.py -i a.b.c.d` where `a.b.c.d` is IP address or hostname that resolves to desired IP address. dispy uses default hostname to resolve to IP address, so if that is setup correctly dispy will use appropriate address.

**Comment by orwel1984** [comment]
-i option seems to work. 
But i don't understand why it works without it on some machines ?

**Comment by pgiri** [comment]
Likely some nodes have their hostname configured such that the names resolve to appropriate IP address and other nodes are not. dispy uses output of `socket.getaddrinfo(socket.gethostname(), None)[0][-1][0]` as IP address. If it gives 127.0.0.1, then you may need to change configuration of hostname / DNS for that server.

**Comment by pgiri** [comment]
You may want to install `netifaces` module; then dispy tries to find configured network address (and avoid loopback address).
